//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Addon {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Addon.dependencies
    /// </jsonId>
    /// <json>
    /// {
    ///  "properties": {
    ///    "addonid": {
    ///      "required": true,
    ///      "type": "string"
    ///    },
    ///    "optional": {
    ///      "required": true,
    ///      "type": "boolean"
    ///    },
    ///    "version": {
    ///      "required": true,
    ///      "type": "string"
    ///    }
    ///  },
    ///  "type": "object"
    ///}
    /// </json>
    public partial class Dependencies : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private string _addonid;
        
        private bool _optional;
        
        private string _version = "";
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="addonid")]
        public string Addonid {
            get {
                return this._addonid;
            }
            set {
                this._addonid = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="optional")]
        public bool Optional {
            get {
                return this._optional;
            }
            set {
                this._optional = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="version")]
        public string Version {
            get {
                return this._version;
            }
            set {
                this._version = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Addonid = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "addonid");
            this.Optional = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<bool>(json, "optional");
            this.Version = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "version", "");
            this.ParseExtension(json);
        }
    }
}
