//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Addon {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Addon.Fields
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Addon.Fields",
    ///  "items": {
    ///    "enums": [
    ///      "name",
    ///      "version",
    ///      "summary",
    ///      "description",
    ///      "path",
    ///      "author",
    ///      "thumbnail",
    ///      "disclaimer",
    ///      "fanart",
    ///      "dependencies",
    ///      "broken",
    ///      "extrainfo",
    ///      "rating",
    ///      "enabled"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    public class Fields : JeanRichard.Xbmc.Lib.JsonRpc.FlagsBase<Fields> {
        
        public static Fields None = new Fields();
        
        public static Fields Name = new Fields("name");
        
        public static Fields Version = new Fields("version");
        
        public static Fields Summary = new Fields("summary");
        
        public static Fields Description = new Fields("description");
        
        public static Fields Path = new Fields("path");
        
        public static Fields Author = new Fields("author");
        
        public static Fields Thumbnail = new Fields("thumbnail");
        
        public static Fields Disclaimer = new Fields("disclaimer");
        
        public static Fields FanArt = new Fields("fanart");
        
        public static Fields Dependencies = new Fields("dependencies");
        
        public static Fields Broken = new Fields("broken");
        
        public static Fields Extrainfo = new Fields("extrainfo");
        
        public static Fields Rating = new Fields("rating");
        
        public static Fields Enabled = new Fields("enabled");
        
        public static Fields All = Fields.Combine(Fields.Name, Fields.Version, Fields.Summary, Fields.Description, Fields.Path, Fields.Author, Fields.Thumbnail, Fields.Disclaimer, Fields.FanArt, Fields.Dependencies, Fields.Broken, Fields.Extrainfo, Fields.Rating, Fields.Enabled);
        

        protected Fields(string value) : base(value)
        {}

        public Fields()
        {}
        
    }
}
