//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Addon {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Addon.Types
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "unknown",
    ///  "enums": [
    ///    "unknown",
    ///    "xbmc.metadata.scraper.albums",
    ///    "xbmc.metadata.scraper.artists",
    ///    "xbmc.metadata.scraper.movies",
    ///    "xbmc.metadata.scraper.musicvideos",
    ///    "xbmc.metadata.scraper.tvshows",
    ///    "xbmc.ui.screensaver",
    ///    "xbmc.player.musicviz",
    ///    "xbmc.python.pluginsource",
    ///    "xbmc.python.script",
    ///    "xbmc.python.weather",
    ///    "xbmc.python.subtitles",
    ///    "xbmc.python.lyrics",
    ///    "xbmc.gui.skin",
    ///    "xbmc.gui.webinterface",
    ///    "xbmc.addon.video",
    ///    "xbmc.addon.audio",
    ///    "xbmc.addon.image",
    ///    "xbmc.addon.executable",
    ///    "xbmc.service"
    ///  ],
    ///  "id": "Addon.Types",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Types : long {
        
        [System.Runtime.Serialization.EnumMember(Value="unknown")]
        Unknown,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.metadata.scraper.albums")]
        Xbmc.Metadata.Scraper.Albums,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.metadata.scraper.artists")]
        Xbmc.Metadata.Scraper.Artists,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.metadata.scraper.movies")]
        Xbmc.Metadata.Scraper.Movies,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.metadata.scraper.musicvideos")]
        Xbmc.Metadata.Scraper.Musicvideos,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.metadata.scraper.tvshows")]
        Xbmc.Metadata.Scraper.Tvshows,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.ui.screensaver")]
        Xbmc.Ui.Screensaver,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.player.musicviz")]
        Xbmc.Player.Musicviz,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.python.pluginsource")]
        Xbmc.Python.Pluginsource,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.python.script")]
        Xbmc.Python.Script,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.python.weather")]
        Xbmc.Python.Weather,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.python.subtitles")]
        Xbmc.Python.Subtitles,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.python.lyrics")]
        Xbmc.Python.Lyrics,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.gui.skin")]
        Xbmc.Gui.Skin,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.gui.webinterface")]
        Xbmc.Gui.Webinterface,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.addon.video")]
        Xbmc.Addon.Video,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.addon.audio")]
        Xbmc.Addon.Audio,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.addon.image")]
        Xbmc.Addon.Image,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.addon.executable")]
        Xbmc.Addon.Executable,
        
        [System.Runtime.Serialization.EnumMember(Value="xbmc.service")]
        Xbmc.Service,
    }
}
