//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Cast
    /// </jsonId>
    /// <json>
    /// {
    ///  "additionalProperties": false,
    ///  "properties": {
    ///    "name": {
    ///      "required": true,
    ///      "type": "string"
    ///    },
    ///    "role": {
    ///      "required": true,
    ///      "type": "string"
    ///    },
    ///    "thumbnail": {
    ///      "default": "",
    ///      "type": "string"
    ///    }
    ///  },
    ///  "type": "object"
    ///}
    /// </json>
    public partial class Cast : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private string _name;
        
        private string _role;
        
        private string _thumbnail = "";
        
        [Newtonsoft.Json.JsonProperty(PropertyName="name")]
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="role")]
        public string Role {
            get {
                return this._role;
            }
            set {
                this._role = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="thumbnail")]
        public string Thumbnail {
            get {
                return this._thumbnail;
            }
            set {
                this._thumbnail = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Name = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "name");
            this.Role = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "role");
            this.Thumbnail = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "thumbnail", "");
        }
    }
}
