//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Playlist.Property {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Playlist.Property.Name
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "type",
    ///  "enums": [
    ///    "type",
    ///    "size"
    ///  ],
    ///  "id": "Playlist.Property.Name",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Name : long {
        
        [System.Runtime.Serialization.EnumMember(Value="type")]
        Type,
        
        [System.Runtime.Serialization.EnumMember(Value="size")]
        Size,
    }
}
