//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.GUI.Property {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// GUI.Property.Value
    /// </jsonId>
    /// <json>
    /// {
    ///  "id": "GUI.Property.Value",
    ///  "properties": {
    ///    "currentcontrol": {
    ///      "properties": {
    ///        "label": {
    ///          "required": true,
    ///          "type": "string"
    ///        }
    ///      },
    ///      "type": "object"
    ///    },
    ///    "currentwindow": {
    ///      "properties": {
    ///        "id": {
    ///          "required": true,
    ///          "type": "integer"
    ///        },
    ///        "label": {
    ///          "required": true,
    ///          "type": "string"
    ///        }
    ///      },
    ///      "type": "object"
    ///    },
    ///    "fullscreen": {
    ///      "default": false,
    ///      "type": "boolean"
    ///    },
    ///    "skin": {
    ///      "properties": {
    ///        "id": {
    ///          "minLength": 1,
    ///          "required": true,
    ///          "type": "string"
    ///        },
    ///        "name": {
    ///          "default": "",
    ///          "type": "string"
    ///        }
    ///      },
    ///      "type": "object"
    ///    }
    ///  },
    ///  "type": "object"
    ///}
    /// </json>
    public partial class Value : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private Object _currentControl;
        
        private Object _currentWindow;
        
        private System.Nullable<bool> _fullScreen = false;
        
        private Object _skin;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="currentcontrol")]
        public Object CurrentControl {
            get {
                return this._currentControl;
            }
            set {
                this._currentControl = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="currentwindow")]
        public Object CurrentWindow {
            get {
                return this._currentWindow;
            }
            set {
                this._currentWindow = value;
            }
        }
        
        /// <remarks>Default: 'False'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="fullscreen")]
        public System.Nullable<bool> FullScreen {
            get {
                return this._fullScreen;
            }
            set {
                this._fullScreen = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="skin")]
        public Object Skin {
            get {
                return this._skin;
            }
            set {
                this._skin = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.CurrentControl = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Object>(json, "currentcontrol");
            this.CurrentWindow = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Object>(json, "currentwindow");
            this.FullScreen = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<bool>>(json, "fullscreen", false);
            this.Skin = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Object>(json, "skin");
            this.ParseExtension(json);
        }
    }
}
