//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.GUI {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// GUI.Window
    /// </jsonId>
    /// <json>
    /// {
    ///  "enums": [
    ///    "home",
    ///    "programs",
    ///    "pictures",
    ///    "filemanager",
    ///    "files",
    ///    "settings",
    ///    "music",
    ///    "video",
    ///    "videos",
    ///    "tv",
    ///    "pvr",
    ///    "pvrguideinfo",
    ///    "pvrrecordinginfo",
    ///    "pvrtimersetting",
    ///    "pvrgroupmanager",
    ///    "pvrchannelmanager",
    ///    "pvrguidesearch",
    ///    "pvrchannelscan",
    ///    "pvrupdateprogress",
    ///    "pvrosdchannels",
    ///    "pvrosdguide",
    ///    "pvrosddirector",
    ///    "pvrosdcutter",
    ///    "pvrosdteletext",
    ///    "systeminfo",
    ///    "testpattern",
    ///    "screencalibration",
    ///    "guicalibration",
    ///    "picturessettings",
    ///    "programssettings",
    ///    "weathersettings",
    ///    "musicsettings",
    ///    "systemsettings",
    ///    "videossettings",
    ///    "networksettings",
    ///    "servicesettings",
    ///    "appearancesettings",
    ///    "pvrsettings",
    ///    "tvsettings",
    ///    "scripts",
    ///    "videofiles",
    ///    "videolibrary",
    ///    "videoplaylist",
    ///    "loginscreen",
    ///    "profiles",
    ///    "skinsettings",
    ///    "addonbrowser",
    ///    "yesnodialog",
    ///    "progressdialog",
    ///    "virtualkeyboard",
    ///    "volumebar",
    ///    "submenu",
    ///    "favourites",
    ///    "contextmenu",
    ///    "infodialog",
    ///    "numericinput",
    ///    "gamepadinput",
    ///    "shutdownmenu",
    ///    "mutebug",
    ///    "playercontrols",
    ///    "seekbar",
    ///    "musicosd",
    ///    "addonsettings",
    ///    "visualisationsettings",
    ///    "visualisationpresetlist",
    ///    "osdvideosettings",
    ///    "osdaudiosettings",
    ///    "videobookmarks",
    ///    "filebrowser",
    ///    "networksetup",
    ///    "mediasource",
    ///    "profilesettings",
    ///    "locksettings",
    ///    "contentsettings",
    ///    "songinformation",
    ///    "smartplaylisteditor",
    ///    "smartplaylistrule",
    ///    "busydialog",
    ///    "pictureinfo",
    ///    "accesspoints",
    ///    "fullscreeninfo",
    ///    "karaokeselector",
    ///    "karaokelargeselector",
    ///    "sliderdialog",
    ///    "addoninformation",
    ///    "musicplaylist",
    ///    "musicfiles",
    ///    "musiclibrary",
    ///    "musicplaylisteditor",
    ///    "teletext",
    ///    "selectdialog",
    ///    "musicinformation",
    ///    "okdialog",
    ///    "movieinformation",
    ///    "textviewer",
    ///    "fullscreenvideo",
    ///    "fullscreenlivetv",
    ///    "visualisation",
    ///    "slideshow",
    ///    "filestackingdialog",
    ///    "karaoke",
    ///    "weather",
    ///    "screensaver",
    ///    "videoosd",
    ///    "videomenu",
    ///    "videotimeseek",
    ///    "musicoverlay",
    ///    "videooverlay",
    ///    "startwindow",
    ///    "startup",
    ///    "peripherals",
    ///    "peripheralsettings",
    ///    "extendedprogressdialog",
    ///    "mediafilter"
    ///  ],
    ///  "id": "GUI.Window",
    ///  "required": true,
    ///  "type": "string"
    ///}
    /// </json>
    public enum Window : long {
        
        [System.Runtime.Serialization.EnumMember(Value="home")]
        Home,
        
        [System.Runtime.Serialization.EnumMember(Value="programs")]
        Programs,
        
        [System.Runtime.Serialization.EnumMember(Value="pictures")]
        Pictures,
        
        [System.Runtime.Serialization.EnumMember(Value="filemanager")]
        FileManager,
        
        [System.Runtime.Serialization.EnumMember(Value="files")]
        Files,
        
        [System.Runtime.Serialization.EnumMember(Value="settings")]
        SetTings,
        
        [System.Runtime.Serialization.EnumMember(Value="music")]
        Music,
        
        [System.Runtime.Serialization.EnumMember(Value="video")]
        Video,
        
        [System.Runtime.Serialization.EnumMember(Value="videos")]
        VideoS,
        
        [System.Runtime.Serialization.EnumMember(Value="tv")]
        TV,
        
        [System.Runtime.Serialization.EnumMember(Value="pvr")]
        Pvr,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrguideinfo")]
        Pvrguideinfo,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrrecordinginfo")]
        Pvrrecordinginfo,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrtimersetting")]
        Pvrtimersetting,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrgroupmanager")]
        Pvrgroupmanager,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrchannelmanager")]
        Pvrchannelmanager,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrguidesearch")]
        Pvrguidesearch,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrchannelscan")]
        Pvrchannelscan,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrupdateprogress")]
        Pvrupdateprogress,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrosdchannels")]
        Pvrosdchannels,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrosdguide")]
        Pvrosdguide,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrosddirector")]
        Pvrosddirector,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrosdcutter")]
        Pvrosdcutter,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrosdteletext")]
        Pvrosdteletext,
        
        [System.Runtime.Serialization.EnumMember(Value="systeminfo")]
        Systeminfo,
        
        [System.Runtime.Serialization.EnumMember(Value="testpattern")]
        Testpattern,
        
        [System.Runtime.Serialization.EnumMember(Value="screencalibration")]
        Screencalibration,
        
        [System.Runtime.Serialization.EnumMember(Value="guicalibration")]
        Guicalibration,
        
        [System.Runtime.Serialization.EnumMember(Value="picturessettings")]
        Picturessettings,
        
        [System.Runtime.Serialization.EnumMember(Value="programssettings")]
        Programssettings,
        
        [System.Runtime.Serialization.EnumMember(Value="weathersettings")]
        Weathersettings,
        
        [System.Runtime.Serialization.EnumMember(Value="musicsettings")]
        MusicSetTings,
        
        [System.Runtime.Serialization.EnumMember(Value="systemsettings")]
        Systemsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="videossettings")]
        VideoSsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="networksettings")]
        Networksettings,
        
        [System.Runtime.Serialization.EnumMember(Value="servicesettings")]
        Servicesettings,
        
        [System.Runtime.Serialization.EnumMember(Value="appearancesettings")]
        Appearancesettings,
        
        [System.Runtime.Serialization.EnumMember(Value="pvrsettings")]
        Pvrsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="tvsettings")]
        TVSetTings,
        
        [System.Runtime.Serialization.EnumMember(Value="scripts")]
        Scripts,
        
        [System.Runtime.Serialization.EnumMember(Value="videofiles")]
        VideoFiles,
        
        [System.Runtime.Serialization.EnumMember(Value="videolibrary")]
        VideoLibrary,
        
        [System.Runtime.Serialization.EnumMember(Value="videoplaylist")]
        VideoPlaylist,
        
        [System.Runtime.Serialization.EnumMember(Value="loginscreen")]
        Loginscreen,
        
        [System.Runtime.Serialization.EnumMember(Value="profiles")]
        Profiles,
        
        [System.Runtime.Serialization.EnumMember(Value="skinsettings")]
        Skinsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="addonbrowser")]
        Addonbrowser,
        
        [System.Runtime.Serialization.EnumMember(Value="yesnodialog")]
        Yesnodialog,
        
        [System.Runtime.Serialization.EnumMember(Value="progressdialog")]
        Progressdialog,
        
        [System.Runtime.Serialization.EnumMember(Value="virtualkeyboard")]
        Virtualkeyboard,
        
        [System.Runtime.Serialization.EnumMember(Value="volumebar")]
        Volumebar,
        
        [System.Runtime.Serialization.EnumMember(Value="submenu")]
        Submenu,
        
        [System.Runtime.Serialization.EnumMember(Value="favourites")]
        Favourites,
        
        [System.Runtime.Serialization.EnumMember(Value="contextmenu")]
        Contextmenu,
        
        [System.Runtime.Serialization.EnumMember(Value="infodialog")]
        Infodialog,
        
        [System.Runtime.Serialization.EnumMember(Value="numericinput")]
        Numericinput,
        
        [System.Runtime.Serialization.EnumMember(Value="gamepadinput")]
        Gamepadinput,
        
        [System.Runtime.Serialization.EnumMember(Value="shutdownmenu")]
        Shutdownmenu,
        
        [System.Runtime.Serialization.EnumMember(Value="mutebug")]
        Mutebug,
        
        [System.Runtime.Serialization.EnumMember(Value="playercontrols")]
        PlayerControls,
        
        [System.Runtime.Serialization.EnumMember(Value="seekbar")]
        Seekbar,
        
        [System.Runtime.Serialization.EnumMember(Value="musicosd")]
        MusicOsd,
        
        [System.Runtime.Serialization.EnumMember(Value="addonsettings")]
        Addonsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="visualisationsettings")]
        Visualisationsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="visualisationpresetlist")]
        Visualisationpresetlist,
        
        [System.Runtime.Serialization.EnumMember(Value="osdvideosettings")]
        Osdvideosettings,
        
        [System.Runtime.Serialization.EnumMember(Value="osdaudiosettings")]
        Osdaudiosettings,
        
        [System.Runtime.Serialization.EnumMember(Value="videobookmarks")]
        VideoBookmarks,
        
        [System.Runtime.Serialization.EnumMember(Value="filebrowser")]
        FileBrowser,
        
        [System.Runtime.Serialization.EnumMember(Value="networksetup")]
        Networksetup,
        
        [System.Runtime.Serialization.EnumMember(Value="mediasource")]
        MediaSource,
        
        [System.Runtime.Serialization.EnumMember(Value="profilesettings")]
        Profilesettings,
        
        [System.Runtime.Serialization.EnumMember(Value="locksettings")]
        Locksettings,
        
        [System.Runtime.Serialization.EnumMember(Value="contentsettings")]
        Contentsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="songinformation")]
        SongInformation,
        
        [System.Runtime.Serialization.EnumMember(Value="smartplaylisteditor")]
        Smartplaylisteditor,
        
        [System.Runtime.Serialization.EnumMember(Value="smartplaylistrule")]
        Smartplaylistrule,
        
        [System.Runtime.Serialization.EnumMember(Value="busydialog")]
        Busydialog,
        
        [System.Runtime.Serialization.EnumMember(Value="pictureinfo")]
        Pictureinfo,
        
        [System.Runtime.Serialization.EnumMember(Value="accesspoints")]
        Accesspoints,
        
        [System.Runtime.Serialization.EnumMember(Value="fullscreeninfo")]
        FullScreeninfo,
        
        [System.Runtime.Serialization.EnumMember(Value="karaokeselector")]
        Karaokeselector,
        
        [System.Runtime.Serialization.EnumMember(Value="karaokelargeselector")]
        Karaokelargeselector,
        
        [System.Runtime.Serialization.EnumMember(Value="sliderdialog")]
        Sliderdialog,
        
        [System.Runtime.Serialization.EnumMember(Value="addoninformation")]
        Addoninformation,
        
        [System.Runtime.Serialization.EnumMember(Value="musicplaylist")]
        MusicPlaylist,
        
        [System.Runtime.Serialization.EnumMember(Value="musicfiles")]
        MusicFiles,
        
        [System.Runtime.Serialization.EnumMember(Value="musiclibrary")]
        MusicLibrary,
        
        [System.Runtime.Serialization.EnumMember(Value="musicplaylisteditor")]
        MusicPlaylistEditor,
        
        [System.Runtime.Serialization.EnumMember(Value="teletext")]
        Teletext,
        
        [System.Runtime.Serialization.EnumMember(Value="selectdialog")]
        Selectdialog,
        
        [System.Runtime.Serialization.EnumMember(Value="musicinformation")]
        MusicInformation,
        
        [System.Runtime.Serialization.EnumMember(Value="okdialog")]
        Okdialog,
        
        [System.Runtime.Serialization.EnumMember(Value="movieinformation")]
        MovieInformation,
        
        [System.Runtime.Serialization.EnumMember(Value="textviewer")]
        Textviewer,
        
        [System.Runtime.Serialization.EnumMember(Value="fullscreenvideo")]
        FullScreenvideo,
        
        [System.Runtime.Serialization.EnumMember(Value="fullscreenlivetv")]
        FullScreenlivetv,
        
        [System.Runtime.Serialization.EnumMember(Value="visualisation")]
        Visualisation,
        
        [System.Runtime.Serialization.EnumMember(Value="slideshow")]
        Slideshow,
        
        [System.Runtime.Serialization.EnumMember(Value="filestackingdialog")]
        FilesTackingdialog,
        
        [System.Runtime.Serialization.EnumMember(Value="karaoke")]
        Karaoke,
        
        [System.Runtime.Serialization.EnumMember(Value="weather")]
        Weather,
        
        [System.Runtime.Serialization.EnumMember(Value="screensaver")]
        Screensaver,
        
        [System.Runtime.Serialization.EnumMember(Value="videoosd")]
        VideoOsd,
        
        [System.Runtime.Serialization.EnumMember(Value="videomenu")]
        VideoMenu,
        
        [System.Runtime.Serialization.EnumMember(Value="videotimeseek")]
        VideoTimeseek,
        
        [System.Runtime.Serialization.EnumMember(Value="musicoverlay")]
        MusicOverlay,
        
        [System.Runtime.Serialization.EnumMember(Value="videooverlay")]
        VideoOverlay,
        
        [System.Runtime.Serialization.EnumMember(Value="startwindow")]
        Startwindow,
        
        [System.Runtime.Serialization.EnumMember(Value="startup")]
        Startup,
        
        [System.Runtime.Serialization.EnumMember(Value="peripherals")]
        Peripherals,
        
        [System.Runtime.Serialization.EnumMember(Value="peripheralsettings")]
        Peripheralsettings,
        
        [System.Runtime.Serialization.EnumMember(Value="extendedprogressdialog")]
        ExtendedProgressdialog,
        
        [System.Runtime.Serialization.EnumMember(Value="mediafilter")]
        MediaFilter,
    }
}
