//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.ItemS {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Items.Sources
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Details.Base",
    ///  "properties": {
    ///    "file": {
    ///      "required": true,
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Sources : JeanRichard.Xbmc.Lib.XbmcEntities.Item.ItemDetailsBase {
        
        private string _file;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="file")]
        public string File {
            get {
                return this._file;
            }
            set {
                this._file = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.File = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "file");
            this.ParseExtension(json);
        }
    }
}
