//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.MovieSet {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.MovieSet.Extended
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.MovieSet",
    ///  "id": "Video.Details.MovieSet.Extended",
    ///  "properties": {
    ///    "limits": {
    ///      "$ref": "List.LimitsReturned",
    ///      "required": true
    ///    },
    ///    "movies": {
    ///      "items": {
    ///        "$ref": "Video.Details.Movie"
    ///      },
    ///      "type": "array"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Extended : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.MovieSet {
        
        private List.LimitsReturned _limits;
        
        private Video.Details.Movie[] _movieS;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="limits")]
        public List.LimitsReturned Limits {
            get {
                return this._limits;
            }
            set {
                this._limits = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="movies")]
        public Video.Details.Movie[] MovieS {
            get {
                return this._movieS;
            }
            set {
                this._movieS = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Limits = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<List.LimitsReturned>(json, "limits");
            this.MovieS = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObjectArray<Video.Details.Movie>(json, "movies");
            this.ParseExtension(json);
        }
    }
}
