//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Global {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Global.IncrementDecrement
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "increment",
    ///  "enums": [
    ///    "increment",
    ///    "decrement"
    ///  ],
    ///  "id": "Global.IncrementDecrement",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Incrementdecrement : long {
        
        [System.Runtime.Serialization.EnumMember(Value="increment")]
        Increment,
        
        [System.Runtime.Serialization.EnumMember(Value="decrement")]
        Decrement,
    }
}
