//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Fields.All
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "List.Fields.All",
    ///  "items": {
    ///    "enums": [
    ///      "title",
    ///      "artist",
    ///      "albumartist",
    ///      "genre",
    ///      "year",
    ///      "rating",
    ///      "album",
    ///      "track",
    ///      "duration",
    ///      "comment",
    ///      "lyrics",
    ///      "musicbrainztrackid",
    ///      "musicbrainzartistid",
    ///      "musicbrainzalbumid",
    ///      "musicbrainzalbumartistid",
    ///      "playcount",
    ///      "fanart",
    ///      "director",
    ///      "trailer",
    ///      "tagline",
    ///      "plot",
    ///      "plotoutline",
    ///      "originaltitle",
    ///      "lastplayed",
    ///      "writer",
    ///      "studio",
    ///      "mpaa",
    ///      "cast",
    ///      "country",
    ///      "imdbnumber",
    ///      "premiered",
    ///      "productioncode",
    ///      "runtime",
    ///      "set",
    ///      "showlink",
    ///      "streamdetails",
    ///      "top250",
    ///      "votes",
    ///      "firstaired",
    ///      "season",
    ///      "episode",
    ///      "showtitle",
    ///      "thumbnail",
    ///      "file",
    ///      "resume",
    ///      "artistid",
    ///      "albumid",
    ///      "tvshowid",
    ///      "setid"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum AllFields : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="albumartist")]
        AlbumArtist = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre = 8,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year = 16,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating = 32,
        
        [System.Runtime.Serialization.EnumMember(Value="album")]
        Album = 64,
        
        [System.Runtime.Serialization.EnumMember(Value="track")]
        Track = 128,
        
        [System.Runtime.Serialization.EnumMember(Value="duration")]
        Duration = 256,
        
        [System.Runtime.Serialization.EnumMember(Value="comment")]
        Comment = 512,
        
        [System.Runtime.Serialization.EnumMember(Value="lyrics")]
        Lyrics = 1024,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainztrackid")]
        MusicBrainzTrackId = 2048,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzartistid")]
        MusicBrainzArtistId = 4096,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzalbumid")]
        MusicBrainzAlbumId = 8192,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzalbumartistid")]
        MusicBrainzAlbumArtistId = 16384,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount = 32768,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 65536,
        
        [System.Runtime.Serialization.EnumMember(Value="director")]
        Director = 131072,
        
        [System.Runtime.Serialization.EnumMember(Value="trailer")]
        Trailer = 262144,
        
        [System.Runtime.Serialization.EnumMember(Value="tagline")]
        Tagline = 524288,
        
        [System.Runtime.Serialization.EnumMember(Value="plot")]
        Plot = 1048576,
        
        [System.Runtime.Serialization.EnumMember(Value="plotoutline")]
        PlotOutline = 2097152,
        
        [System.Runtime.Serialization.EnumMember(Value="originaltitle")]
        OriginalTitle = 4194304,
        
        [System.Runtime.Serialization.EnumMember(Value="lastplayed")]
        LastPlayed = 8388608,
        
        [System.Runtime.Serialization.EnumMember(Value="writer")]
        Writer = 16777216,
        
        [System.Runtime.Serialization.EnumMember(Value="studio")]
        Studio = 33554432,
        
        [System.Runtime.Serialization.EnumMember(Value="mpaa")]
        Mpaa = 67108864,
        
        [System.Runtime.Serialization.EnumMember(Value="cast")]
        Cast = 134217728,
        
        [System.Runtime.Serialization.EnumMember(Value="country")]
        Country = 268435456,
        
        [System.Runtime.Serialization.EnumMember(Value="imdbnumber")]
        ImdbNumber = 536870912,
        
        [System.Runtime.Serialization.EnumMember(Value="premiered")]
        Premiered = 1073741824,
        
        [System.Runtime.Serialization.EnumMember(Value="productioncode")]
        ProductionCode = 2147483648,
        
        [System.Runtime.Serialization.EnumMember(Value="runtime")]
        Runtime = 4294967296,
        
        [System.Runtime.Serialization.EnumMember(Value="set")]
        Set = 8589934592,
        
        [System.Runtime.Serialization.EnumMember(Value="showlink")]
        ShowLink = 17179869184,
        
        [System.Runtime.Serialization.EnumMember(Value="streamdetails")]
        StreamDetails = 34359738368,
        
        [System.Runtime.Serialization.EnumMember(Value="top250")]
        Top250 = 68719476736,
        
        [System.Runtime.Serialization.EnumMember(Value="votes")]
        Votes = 137438953472,
        
        [System.Runtime.Serialization.EnumMember(Value="firstaired")]
        FirstAired = 274877906944,
        
        [System.Runtime.Serialization.EnumMember(Value="season")]
        Season = 549755813888,
        
        [System.Runtime.Serialization.EnumMember(Value="episode")]
        Episode = 1099511627776,
        
        [System.Runtime.Serialization.EnumMember(Value="showtitle")]
        ShowTitle = 2199023255552,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 4398046511104,
        
        [System.Runtime.Serialization.EnumMember(Value="file")]
        File = 8796093022208,
        
        [System.Runtime.Serialization.EnumMember(Value="resume")]
        Resume = 17592186044416,
        
        [System.Runtime.Serialization.EnumMember(Value="artistid")]
        ArtistId = 35184372088832,
        
        [System.Runtime.Serialization.EnumMember(Value="albumid")]
        AlbumId = 70368744177664,
        
        [System.Runtime.Serialization.EnumMember(Value="tvshowid")]
        TVShowId = 140737488355328,
        
        [System.Runtime.Serialization.EnumMember(Value="setid")]
        SetId = 281474976710656,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 562949953421311,
    }
}
