//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.Episode
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.Episode",
    ///  "items": {
    ///    "description": "Requesting the cast field will result in increased response times",
    ///    "enums": [
    ///      "title",
    ///      "plot",
    ///      "votes",
    ///      "rating",
    ///      "writer",
    ///      "firstaired",
    ///      "playcount",
    ///      "runtime",
    ///      "director",
    ///      "productioncode",
    ///      "season",
    ///      "episode",
    ///      "originaltitle",
    ///      "showtitle",
    ///      "cast",
    ///      "streamdetails",
    ///      "lastplayed",
    ///      "fanart",
    ///      "thumbnail",
    ///      "file",
    ///      "resume",
    ///      "tvshowid",
    ///      "dateadded",
    ///      "uniqueid",
    ///      "art"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    public class Episode : JeanRichard.Xbmc.Lib.JsonRpc.FlagsBase<Episode> {
        
        public static Episode None = new Episode();
        
        public static Episode Title = new Episode("title");
        
        public static Episode Plot = new Episode("plot");
        
        public static Episode Votes = new Episode("votes");
        
        public static Episode Rating = new Episode("rating");
        
        public static Episode Writer = new Episode("writer");
        
        public static Episode FirstAired = new Episode("firstaired");
        
        public static Episode PlayCount = new Episode("playcount");
        
        public static Episode Runtime = new Episode("runtime");
        
        public static Episode Director = new Episode("director");
        
        public static Episode ProductionCode = new Episode("productioncode");
        
        public static Episode Season = new Episode("season");
        
        public static Episode Episode = new Episode("episode");
        
        public static Episode OriginalTitle = new Episode("originaltitle");
        
        public static Episode ShowTitle = new Episode("showtitle");
        
        public static Episode Cast = new Episode("cast");
        
        public static Episode StreamDetails = new Episode("streamdetails");
        
        public static Episode LastPlayed = new Episode("lastplayed");
        
        public static Episode FanArt = new Episode("fanart");
        
        public static Episode Thumbnail = new Episode("thumbnail");
        
        public static Episode File = new Episode("file");
        
        public static Episode Resume = new Episode("resume");
        
        public static Episode TVShowId = new Episode("tvshowid");
        
        public static Episode Dateadded = new Episode("dateadded");
        
        public static Episode Uniqueid = new Episode("uniqueid");
        
        public static Episode Art = new Episode("art");
        
        public static Episode All = Episode.Combine(Episode.Title, Episode.Plot, Episode.Votes, Episode.Rating, Episode.Writer, Episode.FirstAired, Episode.PlayCount, Episode.Runtime, Episode.Director, Episode.ProductionCode, Episode.Season, Episode.Episode, Episode.OriginalTitle, Episode.ShowTitle, Episode.Cast, Episode.StreamDetails, Episode.LastPlayed, Episode.FanArt, Episode.Thumbnail, Episode.File, Episode.Resume, Episode.TVShowId, Episode.Dateadded, Episode.Uniqueid, Episode.Art);
        

        protected Episode(string value) : base(value)
        {}

        public Episode()
        {}
        
    }
}
