//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.Movie
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.Movie",
    ///  "items": {
    ///    "description": "Requesting the cast, set, showling and/or resume field will result in increased response times",
    ///    "enums": [
    ///      "title",
    ///      "genre",
    ///      "year",
    ///      "rating",
    ///      "director",
    ///      "trailer",
    ///      "tagline",
    ///      "plot",
    ///      "plotoutline",
    ///      "originaltitle",
    ///      "lastplayed",
    ///      "playcount",
    ///      "writer",
    ///      "studio",
    ///      "mpaa",
    ///      "cast",
    ///      "country",
    ///      "imdbnumber",
    ///      "premiered",
    ///      "productioncode",
    ///      "runtime",
    ///      "set",
    ///      "showlink",
    ///      "streamdetails",
    ///      "top250",
    ///      "votes",
    ///      "fanart",
    ///      "thumbnail",
    ///      "file",
    ///      "sorttitle",
    ///      "resume",
    ///      "setid"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum Movie : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating = 8,
        
        [System.Runtime.Serialization.EnumMember(Value="director")]
        Director = 16,
        
        [System.Runtime.Serialization.EnumMember(Value="trailer")]
        Trailer = 32,
        
        [System.Runtime.Serialization.EnumMember(Value="tagline")]
        Tagline = 64,
        
        [System.Runtime.Serialization.EnumMember(Value="plot")]
        Plot = 128,
        
        [System.Runtime.Serialization.EnumMember(Value="plotoutline")]
        PlotOutline = 256,
        
        [System.Runtime.Serialization.EnumMember(Value="originaltitle")]
        OriginalTitle = 512,
        
        [System.Runtime.Serialization.EnumMember(Value="lastplayed")]
        LastPlayed = 1024,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount = 2048,
        
        [System.Runtime.Serialization.EnumMember(Value="writer")]
        Writer = 4096,
        
        [System.Runtime.Serialization.EnumMember(Value="studio")]
        Studio = 8192,
        
        [System.Runtime.Serialization.EnumMember(Value="mpaa")]
        Mpaa = 16384,
        
        [System.Runtime.Serialization.EnumMember(Value="cast")]
        Cast = 32768,
        
        [System.Runtime.Serialization.EnumMember(Value="country")]
        Country = 65536,
        
        [System.Runtime.Serialization.EnumMember(Value="imdbnumber")]
        ImdbNumber = 131072,
        
        [System.Runtime.Serialization.EnumMember(Value="premiered")]
        Premiered = 262144,
        
        [System.Runtime.Serialization.EnumMember(Value="productioncode")]
        ProductionCode = 524288,
        
        [System.Runtime.Serialization.EnumMember(Value="runtime")]
        Runtime = 1048576,
        
        [System.Runtime.Serialization.EnumMember(Value="set")]
        Set = 2097152,
        
        [System.Runtime.Serialization.EnumMember(Value="showlink")]
        ShowLink = 4194304,
        
        [System.Runtime.Serialization.EnumMember(Value="streamdetails")]
        StreamDetails = 8388608,
        
        [System.Runtime.Serialization.EnumMember(Value="top250")]
        Top250 = 16777216,
        
        [System.Runtime.Serialization.EnumMember(Value="votes")]
        Votes = 33554432,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 67108864,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 134217728,
        
        [System.Runtime.Serialization.EnumMember(Value="file")]
        File = 268435456,
        
        [System.Runtime.Serialization.EnumMember(Value="sorttitle")]
        SortTitle = 536870912,
        
        [System.Runtime.Serialization.EnumMember(Value="resume")]
        Resume = 1073741824,
        
        [System.Runtime.Serialization.EnumMember(Value="setid")]
        SetId = 2147483648,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 4294967295,
    }
}
