//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.Movie
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.Movie",
    ///  "items": {
    ///    "description": "Requesting the cast, showlink and/or tag field will result in increased response times",
    ///    "enums": [
    ///      "title",
    ///      "genre",
    ///      "year",
    ///      "rating",
    ///      "director",
    ///      "trailer",
    ///      "tagline",
    ///      "plot",
    ///      "plotoutline",
    ///      "originaltitle",
    ///      "lastplayed",
    ///      "playcount",
    ///      "writer",
    ///      "studio",
    ///      "mpaa",
    ///      "cast",
    ///      "country",
    ///      "imdbnumber",
    ///      "runtime",
    ///      "set",
    ///      "showlink",
    ///      "streamdetails",
    ///      "top250",
    ///      "votes",
    ///      "fanart",
    ///      "thumbnail",
    ///      "file",
    ///      "sorttitle",
    ///      "resume",
    ///      "setid",
    ///      "dateadded",
    ///      "tag",
    ///      "art"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    public class Movie : JeanRichard.Xbmc.Lib.JsonRpc.FlagsBase<Movie> {
        
        public static Movie None = new Movie();
        
        public static Movie Title = new Movie("title");
        
        public static Movie Genre = new Movie("genre");
        
        public static Movie Year = new Movie("year");
        
        public static Movie Rating = new Movie("rating");
        
        public static Movie Director = new Movie("director");
        
        public static Movie Trailer = new Movie("trailer");
        
        public static Movie Tagline = new Movie("tagline");
        
        public static Movie Plot = new Movie("plot");
        
        public static Movie PlotOutline = new Movie("plotoutline");
        
        public static Movie OriginalTitle = new Movie("originaltitle");
        
        public static Movie LastPlayed = new Movie("lastplayed");
        
        public static Movie PlayCount = new Movie("playcount");
        
        public static Movie Writer = new Movie("writer");
        
        public static Movie Studio = new Movie("studio");
        
        public static Movie Mpaa = new Movie("mpaa");
        
        public static Movie Cast = new Movie("cast");
        
        public static Movie Country = new Movie("country");
        
        public static Movie ImdbNumber = new Movie("imdbnumber");
        
        public static Movie Runtime = new Movie("runtime");
        
        public static Movie Set = new Movie("set");
        
        public static Movie ShowLink = new Movie("showlink");
        
        public static Movie StreamDetails = new Movie("streamdetails");
        
        public static Movie Top250 = new Movie("top250");
        
        public static Movie Votes = new Movie("votes");
        
        public static Movie FanArt = new Movie("fanart");
        
        public static Movie Thumbnail = new Movie("thumbnail");
        
        public static Movie File = new Movie("file");
        
        public static Movie SortTitle = new Movie("sorttitle");
        
        public static Movie Resume = new Movie("resume");
        
        public static Movie SetId = new Movie("setid");
        
        public static Movie Dateadded = new Movie("dateadded");
        
        public static Movie Tag = new Movie("tag");
        
        public static Movie Art = new Movie("art");
        
        public static Movie All = Movie.Combine(Movie.Title, Movie.Genre, Movie.Year, Movie.Rating, Movie.Director, Movie.Trailer, Movie.Tagline, Movie.Plot, Movie.PlotOutline, Movie.OriginalTitle, Movie.LastPlayed, Movie.PlayCount, Movie.Writer, Movie.Studio, Movie.Mpaa, Movie.Cast, Movie.Country, Movie.ImdbNumber, Movie.Runtime, Movie.Set, Movie.ShowLink, Movie.StreamDetails, Movie.Top250, Movie.Votes, Movie.FanArt, Movie.Thumbnail, Movie.File, Movie.SortTitle, Movie.Resume, Movie.SetId, Movie.Dateadded, Movie.Tag, Movie.Art);
        

        protected Movie(string value) : base(value)
        {}

        public Movie()
        {}
        
    }
}
