//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.MovieSet
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.MovieSet",
    ///  "items": {
    ///    "enums": [
    ///      "title",
    ///      "playcount",
    ///      "fanart",
    ///      "thumbnail"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum MovieSet : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 8,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 15,
    }
}
