//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.MovieSet
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.MovieSet",
    ///  "items": {
    ///    "enums": [
    ///      "title",
    ///      "playcount",
    ///      "fanart",
    ///      "thumbnail",
    ///      "art"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    public class MovieSet : JeanRichard.Xbmc.Lib.JsonRpc.FlagsBase<MovieSet> {
        
        public static MovieSet None = new MovieSet();
        
        public static MovieSet Title = new MovieSet("title");
        
        public static MovieSet PlayCount = new MovieSet("playcount");
        
        public static MovieSet FanArt = new MovieSet("fanart");
        
        public static MovieSet Thumbnail = new MovieSet("thumbnail");
        
        public static MovieSet Art = new MovieSet("art");
        
        public static MovieSet All = MovieSet.Combine(MovieSet.Title, MovieSet.PlayCount, MovieSet.FanArt, MovieSet.Thumbnail, MovieSet.Art);
        

        protected MovieSet(string value) : base(value)
        {}

        public MovieSet()
        {}
        
    }
}
