//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.MusicVideo
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.MusicVideo",
    ///  "items": {
    ///    "description": "Requesting the resume field will result in increased response times",
    ///    "enums": [
    ///      "title",
    ///      "playcount",
    ///      "runtime",
    ///      "director",
    ///      "studio",
    ///      "year",
    ///      "plot",
    ///      "album",
    ///      "artist",
    ///      "genre",
    ///      "track",
    ///      "streamdetails",
    ///      "lastplayed",
    ///      "fanart",
    ///      "thumbnail",
    ///      "file",
    ///      "resume"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum MusicVideo : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="runtime")]
        Runtime = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="director")]
        Director = 8,
        
        [System.Runtime.Serialization.EnumMember(Value="studio")]
        Studio = 16,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year = 32,
        
        [System.Runtime.Serialization.EnumMember(Value="plot")]
        Plot = 64,
        
        [System.Runtime.Serialization.EnumMember(Value="album")]
        Album = 128,
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist = 256,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre = 512,
        
        [System.Runtime.Serialization.EnumMember(Value="track")]
        Track = 1024,
        
        [System.Runtime.Serialization.EnumMember(Value="streamdetails")]
        StreamDetails = 2048,
        
        [System.Runtime.Serialization.EnumMember(Value="lastplayed")]
        LastPlayed = 4096,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 8192,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 16384,
        
        [System.Runtime.Serialization.EnumMember(Value="file")]
        File = 32768,
        
        [System.Runtime.Serialization.EnumMember(Value="resume")]
        Resume = 65536,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 131071,
    }
}
