//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.Season
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.Season",
    ///  "items": {
    ///    "enums": [
    ///      "season",
    ///      "showtitle",
    ///      "playcount",
    ///      "episode",
    ///      "fanart",
    ///      "thumbnail",
    ///      "tvshowid"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum Season : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="season")]
        Season = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="showtitle")]
        ShowTitle = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="episode")]
        Episode = 8,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 16,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 32,
        
        [System.Runtime.Serialization.EnumMember(Value="tvshowid")]
        TVShowId = 64,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 127,
    }
}
