//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.Season
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.Season",
    ///  "items": {
    ///    "enums": [
    ///      "season",
    ///      "showtitle",
    ///      "playcount",
    ///      "episode",
    ///      "fanart",
    ///      "thumbnail",
    ///      "tvshowid",
    ///      "watchedepisodes",
    ///      "art"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    public class Season : JeanRichard.Xbmc.Lib.JsonRpc.FlagsBase<Season> {
        
        public static Season None = new Season();
        
        public static Season Season = new Season("season");
        
        public static Season ShowTitle = new Season("showtitle");
        
        public static Season PlayCount = new Season("playcount");
        
        public static Season Episode = new Season("episode");
        
        public static Season FanArt = new Season("fanart");
        
        public static Season Thumbnail = new Season("thumbnail");
        
        public static Season TVShowId = new Season("tvshowid");
        
        public static Season Watchedepisodes = new Season("watchedepisodes");
        
        public static Season Art = new Season("art");
        
        public static Season All = Season.Combine(Season.Season, Season.ShowTitle, Season.PlayCount, Season.Episode, Season.FanArt, Season.Thumbnail, Season.TVShowId, Season.Watchedepisodes, Season.Art);
        

        protected Season(string value) : base(value)
        {}

        public Season()
        {}
        
    }
}
