//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.TVShow
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.TVShow",
    ///  "items": {
    ///    "description": "Requesting the cast field will result in increased response times",
    ///    "enums": [
    ///      "title",
    ///      "genre",
    ///      "year",
    ///      "rating",
    ///      "plot",
    ///      "studio",
    ///      "mpaa",
    ///      "cast",
    ///      "playcount",
    ///      "episode",
    ///      "imdbnumber",
    ///      "premiered",
    ///      "votes",
    ///      "lastplayed",
    ///      "fanart",
    ///      "thumbnail",
    ///      "file",
    ///      "originaltitle",
    ///      "sorttitle",
    ///      "episodeguide"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum TVShow : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating = 8,
        
        [System.Runtime.Serialization.EnumMember(Value="plot")]
        Plot = 16,
        
        [System.Runtime.Serialization.EnumMember(Value="studio")]
        Studio = 32,
        
        [System.Runtime.Serialization.EnumMember(Value="mpaa")]
        Mpaa = 64,
        
        [System.Runtime.Serialization.EnumMember(Value="cast")]
        Cast = 128,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount = 256,
        
        [System.Runtime.Serialization.EnumMember(Value="episode")]
        Episode = 512,
        
        [System.Runtime.Serialization.EnumMember(Value="imdbnumber")]
        ImdbNumber = 1024,
        
        [System.Runtime.Serialization.EnumMember(Value="premiered")]
        Premiered = 2048,
        
        [System.Runtime.Serialization.EnumMember(Value="votes")]
        Votes = 4096,
        
        [System.Runtime.Serialization.EnumMember(Value="lastplayed")]
        LastPlayed = 8192,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 16384,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 32768,
        
        [System.Runtime.Serialization.EnumMember(Value="file")]
        File = 65536,
        
        [System.Runtime.Serialization.EnumMember(Value="originaltitle")]
        OriginalTitle = 131072,
        
        [System.Runtime.Serialization.EnumMember(Value="sorttitle")]
        SortTitle = 262144,
        
        [System.Runtime.Serialization.EnumMember(Value="episodeguide")]
        EpisodeGuide = 524288,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 1048575,
    }
}
