//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Fields.TVShow
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Video.Fields.TVShow",
    ///  "items": {
    ///    "description": "Requesting the cast field will result in increased response times",
    ///    "enums": [
    ///      "title",
    ///      "genre",
    ///      "year",
    ///      "rating",
    ///      "plot",
    ///      "studio",
    ///      "mpaa",
    ///      "cast",
    ///      "playcount",
    ///      "episode",
    ///      "imdbnumber",
    ///      "premiered",
    ///      "votes",
    ///      "lastplayed",
    ///      "fanart",
    ///      "thumbnail",
    ///      "file",
    ///      "originaltitle",
    ///      "sorttitle",
    ///      "episodeguide",
    ///      "season",
    ///      "watchedepisodes",
    ///      "dateadded",
    ///      "tag",
    ///      "art"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    public class TVShow : JeanRichard.Xbmc.Lib.JsonRpc.FlagsBase<TVShow> {
        
        public static TVShow None = new TVShow();
        
        public static TVShow Title = new TVShow("title");
        
        public static TVShow Genre = new TVShow("genre");
        
        public static TVShow Year = new TVShow("year");
        
        public static TVShow Rating = new TVShow("rating");
        
        public static TVShow Plot = new TVShow("plot");
        
        public static TVShow Studio = new TVShow("studio");
        
        public static TVShow Mpaa = new TVShow("mpaa");
        
        public static TVShow Cast = new TVShow("cast");
        
        public static TVShow PlayCount = new TVShow("playcount");
        
        public static TVShow Episode = new TVShow("episode");
        
        public static TVShow ImdbNumber = new TVShow("imdbnumber");
        
        public static TVShow Premiered = new TVShow("premiered");
        
        public static TVShow Votes = new TVShow("votes");
        
        public static TVShow LastPlayed = new TVShow("lastplayed");
        
        public static TVShow FanArt = new TVShow("fanart");
        
        public static TVShow Thumbnail = new TVShow("thumbnail");
        
        public static TVShow File = new TVShow("file");
        
        public static TVShow OriginalTitle = new TVShow("originaltitle");
        
        public static TVShow SortTitle = new TVShow("sorttitle");
        
        public static TVShow EpisodeGuide = new TVShow("episodeguide");
        
        public static TVShow Season = new TVShow("season");
        
        public static TVShow Watchedepisodes = new TVShow("watchedepisodes");
        
        public static TVShow Dateadded = new TVShow("dateadded");
        
        public static TVShow Tag = new TVShow("tag");
        
        public static TVShow Art = new TVShow("art");
        
        public static TVShow All = TVShow.Combine(TVShow.Title, TVShow.Genre, TVShow.Year, TVShow.Rating, TVShow.Plot, TVShow.Studio, TVShow.Mpaa, TVShow.Cast, TVShow.PlayCount, TVShow.Episode, TVShow.ImdbNumber, TVShow.Premiered, TVShow.Votes, TVShow.LastPlayed, TVShow.FanArt, TVShow.Thumbnail, TVShow.File, TVShow.OriginalTitle, TVShow.SortTitle, TVShow.EpisodeGuide, TVShow.Season, TVShow.Watchedepisodes, TVShow.Dateadded, TVShow.Tag, TVShow.Art);
        

        protected TVShow(string value) : base(value)
        {}

        public TVShow()
        {}
        
    }
}
