//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Media {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Media.Details.Base
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Details.Base",
    ///  "id": "Media.Details.Base",
    ///  "properties": {
    ///    "fanart": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "thumbnail": {
    ///      "default": "",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class MediaDetailsBase : JeanRichard.Xbmc.Lib.XbmcEntities.Item.ItemDetailsBase {
        
        private string _fanArt = "";
        
        private string _thumbnail = "";
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="fanart")]
        public string FanArt {
            get {
                return this._fanArt;
            }
            set {
                this._fanArt = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="thumbnail")]
        public string Thumbnail {
            get {
                return this._thumbnail;
            }
            set {
                this._thumbnail = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.FanArt = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "fanart", "");
            this.Thumbnail = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "thumbnail", "");
            this.ParseExtension(json);
        }
    }
}
