//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.Base
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Media.Details.Base",
    ///  "id": "Video.Details.Base",
    ///  "properties": {
    ///    "art": {
    ///      "$ref": "Media.Artwork"
    ///    },
    ///    "playcount": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Base : JeanRichard.Xbmc.Lib.XbmcEntities.Media.MediaDetailsBase {
        
        private Media.Artwork _art;
        
        private System.Nullable<int> _playCount = 0;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="art")]
        public Media.Artwork Art {
            get {
                return this._art;
            }
            set {
                this._art = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="playcount")]
        public System.Nullable<int> PlayCount {
            get {
                return this._playCount;
            }
            set {
                this._playCount = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Art = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Media.Artwork>(json, "art");
            this.PlayCount = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "playcount", 0);
            this.ParseExtension(json);
        }
    }
}
