//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.Episode
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.File",
    ///  "id": "Video.Details.Episode",
    ///  "properties": {
    ///    "cast": {
    ///      "$ref": "Video.Cast"
    ///    },
    ///    "episode": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    },
    ///    "episodeid": {
    ///      "$ref": "Library.Id",
    ///      "required": true
    ///    },
    ///    "firstaired": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "originaltitle": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "productioncode": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "rating": {
    ///      "default": 0,
    ///      "type": "number"
    ///    },
    ///    "season": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    },
    ///    "showtitle": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "tvshowid": {
    ///      "$ref": "Library.Id",
    ///      "default": -1
    ///    },
    ///    "votes": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "writer": {
    ///      "default": "",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Episode : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.File {
        
        private Video.Cast[] _cast;
        
        private System.Nullable<int> _episode = 0;
        
        private System.Nullable<int> _episodeId = -1;
        
        private string _firstAired = "";
        
        private string _originalTitle = "";
        
        private string _productionCode = "";
        
        private System.Nullable<decimal> _rating = 0m;
        
        private System.Nullable<int> _season = 0;
        
        private string _showTitle = "";
        
        private System.Nullable<int> _tvShowId = -1;
        
        private string _votes = "";
        
        private string _writer = "";
        
        [Newtonsoft.Json.JsonProperty(PropertyName="cast")]
        public Video.Cast[] Cast {
            get {
                return this._cast;
            }
            set {
                this._cast = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="episode")]
        public System.Nullable<int> Episode {
            get {
                return this._episode;
            }
            set {
                this._episode = value;
            }
        }
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="episodeid")]
        public System.Nullable<int> EpisodeId {
            get {
                return this._episodeId;
            }
            set {
                this._episodeId = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="firstaired")]
        public string FirstAired {
            get {
                return this._firstAired;
            }
            set {
                this._firstAired = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="originaltitle")]
        public string OriginalTitle {
            get {
                return this._originalTitle;
            }
            set {
                this._originalTitle = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="productioncode")]
        public string ProductionCode {
            get {
                return this._productionCode;
            }
            set {
                this._productionCode = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="rating")]
        public System.Nullable<decimal> Rating {
            get {
                return this._rating;
            }
            set {
                this._rating = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="season")]
        public System.Nullable<int> Season {
            get {
                return this._season;
            }
            set {
                this._season = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="showtitle")]
        public string ShowTitle {
            get {
                return this._showTitle;
            }
            set {
                this._showTitle = value;
            }
        }
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="tvshowid")]
        public System.Nullable<int> TVShowId {
            get {
                return this._tvShowId;
            }
            set {
                this._tvShowId = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="votes")]
        public string Votes {
            get {
                return this._votes;
            }
            set {
                this._votes = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="writer")]
        public string Writer {
            get {
                return this._writer;
            }
            set {
                this._writer = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Cast = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObjectArray<Video.Cast>(json, "cast");
            this.Episode = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "episode", 0);
            this.EpisodeId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "episodeid", -1);
            this.FirstAired = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "firstaired", "");
            this.OriginalTitle = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "originaltitle", "");
            this.ProductionCode = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "productioncode", "");
            this.Rating = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<decimal>>(json, "rating", 0m);
            this.Season = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "season", 0);
            this.ShowTitle = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "showtitle", "");
            this.TVShowId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "tvshowid", -1);
            this.Votes = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "votes", "");
            this.Writer = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "writer", "");
        }
    }
}
