//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.File
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.Item",
    ///  "id": "Video.Details.File",
    ///  "properties": {
    ///    "director": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "resume": {
    ///      "$ref": "Video.Resume"
    ///    },
    ///    "runtime": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "streamdetails": {
    ///      "$ref": "Video.Streams"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class File : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.Item {
        
        private string _director = "";
        
        private Video.Resume _resume;
        
        private string _runtime = "";
        
        private Video.Streams _streamDetails;
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="director")]
        public string Director {
            get {
                return this._director;
            }
            set {
                this._director = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="resume")]
        public Video.Resume Resume {
            get {
                return this._resume;
            }
            set {
                this._resume = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="runtime")]
        public string Runtime {
            get {
                return this._runtime;
            }
            set {
                this._runtime = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="streamdetails")]
        public Video.Streams StreamDetails {
            get {
                return this._streamDetails;
            }
            set {
                this._streamDetails = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Director = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "director", "");
            this.Resume = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Video.Resume>(json, "resume");
            this.Runtime = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "runtime", "");
            this.StreamDetails = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Video.Streams>(json, "streamdetails");
        }
    }
}
