//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.File
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.Item",
    ///  "id": "Video.Details.File",
    ///  "properties": {
    ///    "director": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "resume": {
    ///      "$ref": "Video.Resume"
    ///    },
    ///    "runtime": {
    ///      "default": 0,
    ///      "description": "Runtime in seconds",
    ///      "type": "integer"
    ///    },
    ///    "streamdetails": {
    ///      "$ref": "Video.Streams"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class File : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.Item {
        
        private string[] _director;
        
        private Video.Resume _resume;
        
        private System.Nullable<int> _runtime = 0;
        
        private Video.Streams _streamDetails;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="director")]
        public string[] Director {
            get {
                return this._director;
            }
            set {
                this._director = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="resume")]
        public Video.Resume Resume {
            get {
                return this._resume;
            }
            set {
                this._resume = value;
            }
        }
        
        /// <summary>
        /// Runtime in seconds
        /// </summary>
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="runtime")]
        public System.Nullable<int> Runtime {
            get {
                return this._runtime;
            }
            set {
                this._runtime = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="streamdetails")]
        public Video.Streams StreamDetails {
            get {
                return this._streamDetails;
            }
            set {
                this._streamDetails = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Director = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "director");
            this.Resume = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Video.Resume>(json, "resume");
            this.Runtime = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "runtime", 0);
            this.StreamDetails = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Video.Streams>(json, "streamdetails");
            this.ParseExtension(json);
        }
    }
}
