//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.Item
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.Media",
    ///  "id": "Video.Details.Item",
    ///  "properties": {
    ///    "file": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "lastplayed": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "plot": {
    ///      "default": "",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Item : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.Media {
        
        private string _file = "";
        
        private string _lastPlayed = "";
        
        private string _plot = "";
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="file")]
        public string File {
            get {
                return this._file;
            }
            set {
                this._file = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="lastplayed")]
        public string LastPlayed {
            get {
                return this._lastPlayed;
            }
            set {
                this._lastPlayed = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="plot")]
        public string Plot {
            get {
                return this._plot;
            }
            set {
                this._plot = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.File = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "file", "");
            this.LastPlayed = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "lastplayed", "");
            this.Plot = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "plot", "");
        }
    }
}
