//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.Movie
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.File",
    ///  "id": "Video.Details.Movie",
    ///  "properties": {
    ///    "cast": {
    ///      "$ref": "Video.Cast"
    ///    },
    ///    "country": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "genre": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "imdbnumber": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "movieid": {
    ///      "$ref": "Library.Id",
    ///      "required": true
    ///    },
    ///    "mpaa": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "originaltitle": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "plotoutline": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "rating": {
    ///      "default": 0,
    ///      "type": "number"
    ///    },
    ///    "set": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "setid": {
    ///      "$ref": "Library.Id",
    ///      "default": -1
    ///    },
    ///    "showlink": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "sorttitle": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "studio": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "tag": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "tagline": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "top250": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    },
    ///    "trailer": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "votes": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "writer": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "year": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Movie : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.File {
        
        private Video.Cast[] _cast;
        
        private string[] _country;
        
        private string[] _genre;
        
        private string _imdbNumber = "";
        
        private System.Nullable<int> _movieId = -1;
        
        private string _mpaa = "";
        
        private string _originalTitle = "";
        
        private string _plotOutline = "";
        
        private System.Nullable<decimal> _rating = 0m;
        
        private string _set = "";
        
        private System.Nullable<int> _setId = -1;
        
        private string[] _showLink;
        
        private string _sortTitle = "";
        
        private string[] _studio;
        
        private string[] _tag;
        
        private string _tagline = "";
        
        private System.Nullable<int> _top250 = 0;
        
        private string _trailer = "";
        
        private string _votes = "";
        
        private string[] _writer;
        
        private System.Nullable<int> _year = 0;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="cast")]
        public Video.Cast[] Cast {
            get {
                return this._cast;
            }
            set {
                this._cast = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="country")]
        public string[] Country {
            get {
                return this._country;
            }
            set {
                this._country = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="genre")]
        public string[] Genre {
            get {
                return this._genre;
            }
            set {
                this._genre = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="imdbnumber")]
        public string ImdbNumber {
            get {
                return this._imdbNumber;
            }
            set {
                this._imdbNumber = value;
            }
        }
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="movieid")]
        public System.Nullable<int> MovieId {
            get {
                return this._movieId;
            }
            set {
                this._movieId = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="mpaa")]
        public string Mpaa {
            get {
                return this._mpaa;
            }
            set {
                this._mpaa = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="originaltitle")]
        public string OriginalTitle {
            get {
                return this._originalTitle;
            }
            set {
                this._originalTitle = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="plotoutline")]
        public string PlotOutline {
            get {
                return this._plotOutline;
            }
            set {
                this._plotOutline = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="rating")]
        public System.Nullable<decimal> Rating {
            get {
                return this._rating;
            }
            set {
                this._rating = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="set")]
        public string Set {
            get {
                return this._set;
            }
            set {
                this._set = value;
            }
        }
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="setid")]
        public System.Nullable<int> SetId {
            get {
                return this._setId;
            }
            set {
                this._setId = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="showlink")]
        public string[] ShowLink {
            get {
                return this._showLink;
            }
            set {
                this._showLink = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="sorttitle")]
        public string SortTitle {
            get {
                return this._sortTitle;
            }
            set {
                this._sortTitle = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="studio")]
        public string[] Studio {
            get {
                return this._studio;
            }
            set {
                this._studio = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="tag")]
        public string[] Tag {
            get {
                return this._tag;
            }
            set {
                this._tag = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="tagline")]
        public string Tagline {
            get {
                return this._tagline;
            }
            set {
                this._tagline = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="top250")]
        public System.Nullable<int> Top250 {
            get {
                return this._top250;
            }
            set {
                this._top250 = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="trailer")]
        public string Trailer {
            get {
                return this._trailer;
            }
            set {
                this._trailer = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="votes")]
        public string Votes {
            get {
                return this._votes;
            }
            set {
                this._votes = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="writer")]
        public string[] Writer {
            get {
                return this._writer;
            }
            set {
                this._writer = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="year")]
        public System.Nullable<int> Year {
            get {
                return this._year;
            }
            set {
                this._year = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Cast = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObjectArray<Video.Cast>(json, "cast");
            this.Country = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "country");
            this.Genre = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "genre");
            this.ImdbNumber = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "imdbnumber", "");
            this.MovieId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "movieid", -1);
            this.Mpaa = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "mpaa", "");
            this.OriginalTitle = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "originaltitle", "");
            this.PlotOutline = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "plotoutline", "");
            this.Rating = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<decimal>>(json, "rating", 0m);
            this.Set = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "set", "");
            this.SetId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "setid", -1);
            this.ShowLink = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "showlink");
            this.SortTitle = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "sorttitle", "");
            this.Studio = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "studio");
            this.Tag = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "tag");
            this.Tagline = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "tagline", "");
            this.Top250 = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "top250", 0);
            this.Trailer = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "trailer", "");
            this.Votes = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "votes", "");
            this.Writer = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "writer");
            this.Year = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "year", 0);
            this.ParseExtension(json);
        }
    }
}
