//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.MovieSet
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.Media",
    ///  "id": "Video.Details.MovieSet",
    ///  "properties": {
    ///    "setid": {
    ///      "$ref": "Library.Id",
    ///      "required": true
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class MovieSet : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.Media {
        
        private System.Nullable<int> _setId = -1;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="setid")]
        public System.Nullable<int> SetId {
            get {
                return this._setId;
            }
            set {
                this._setId = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.SetId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "setid", -1);
            this.ParseExtension(json);
        }
    }
}
