//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.MusicVideo
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.File",
    ///  "id": "Video.Details.MusicVideo",
    ///  "properties": {
    ///    "album": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "artist": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "genre": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "musicvideoid": {
    ///      "$ref": "Library.Id",
    ///      "required": true
    ///    },
    ///    "studio": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "tag": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "track": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    },
    ///    "year": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class MusicVideo : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.File {
        
        private string _album = "";
        
        private string[] _artist;
        
        private string[] _genre;
        
        private System.Nullable<int> _musicVideoId = -1;
        
        private string[] _studio;
        
        private string[] _tag;
        
        private System.Nullable<int> _track = 0;
        
        private System.Nullable<int> _year = 0;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="album")]
        public string Album {
            get {
                return this._album;
            }
            set {
                this._album = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="artist")]
        public string[] Artist {
            get {
                return this._artist;
            }
            set {
                this._artist = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="genre")]
        public string[] Genre {
            get {
                return this._genre;
            }
            set {
                this._genre = value;
            }
        }
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="musicvideoid")]
        public System.Nullable<int> MusicVideoId {
            get {
                return this._musicVideoId;
            }
            set {
                this._musicVideoId = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="studio")]
        public string[] Studio {
            get {
                return this._studio;
            }
            set {
                this._studio = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="tag")]
        public string[] Tag {
            get {
                return this._tag;
            }
            set {
                this._tag = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="track")]
        public System.Nullable<int> Track {
            get {
                return this._track;
            }
            set {
                this._track = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="year")]
        public System.Nullable<int> Year {
            get {
                return this._year;
            }
            set {
                this._year = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Album = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "album", "");
            this.Artist = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "artist");
            this.Genre = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "genre");
            this.MusicVideoId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "musicvideoid", -1);
            this.Studio = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "studio");
            this.Tag = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "tag");
            this.Track = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "track", 0);
            this.Year = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "year", 0);
            this.ParseExtension(json);
        }
    }
}
