//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Video.Details.Season
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Video.Details.Base",
    ///  "id": "Video.Details.Season",
    ///  "properties": {
    ///    "episode": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    },
    ///    "season": {
    ///      "required": true,
    ///      "type": "integer"
    ///    },
    ///    "showtitle": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "tvshowid": {
    ///      "$ref": "Library.Id",
    ///      "default": -1
    ///    },
    ///    "watchedepisodes": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Season : JeanRichard.Xbmc.Lib.XbmcEntities.Video.Details.Base {
        
        private System.Nullable<int> _episode = 0;
        
        private int _season;
        
        private string _showTitle = "";
        
        private System.Nullable<int> _tvShowId = -1;
        
        private System.Nullable<int> _watchedepisodes = 0;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="episode")]
        public System.Nullable<int> Episode {
            get {
                return this._episode;
            }
            set {
                this._episode = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="season")]
        public int Season {
            get {
                return this._season;
            }
            set {
                this._season = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="showtitle")]
        public string ShowTitle {
            get {
                return this._showTitle;
            }
            set {
                this._showTitle = value;
            }
        }
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="tvshowid")]
        public System.Nullable<int> TVShowId {
            get {
                return this._tvShowId;
            }
            set {
                this._tvShowId = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="watchedepisodes")]
        public System.Nullable<int> Watchedepisodes {
            get {
                return this._watchedepisodes;
            }
            set {
                this._watchedepisodes = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Episode = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "episode", 0);
            this.Season = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<int>(json, "season");
            this.ShowTitle = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "showtitle", "");
            this.TVShowId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "tvshowid", -1);
            this.Watchedepisodes = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "watchedepisodes", 0);
            this.ParseExtension(json);
        }
    }
}
