//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Item {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Item.File
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "List.Item.All",
    ///  "id": "List.Item.File",
    ///  "properties": {
    ///    "file": {
    ///      "required": true,
    ///      "type": "string"
    ///    },
    ///    "filetype": {
    ///      "enums": [
    ///        "file",
    ///        "directory"
    ///      ],
    ///      "required": true,
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class File : JeanRichard.Xbmc.Lib.XbmcEntities.List.Item.All {
        
        private string _file;
        
        private List.Item.FileType _fileType;
        
        [Newtonsoft.Json.JsonProperty(PropertyName="file")]
        public string File {
            get {
                return this._file;
            }
            set {
                this._file = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="filetype")]
        public List.Item.FileType FileType {
            get {
                return this._fileType;
            }
            set {
                this._fileType = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.File = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "file");
            this.FileType = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseEnum<List.Item.FileType>(json, "filetype");
        }
    }
}
