//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Audio.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Audio.Fields.Album
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Audio.Fields.Album",
    ///  "items": {
    ///    "enums": [
    ///      "title",
    ///      "description",
    ///      "artist",
    ///      "genre",
    ///      "theme",
    ///      "mood",
    ///      "style",
    ///      "type",
    ///      "albumlabel",
    ///      "rating",
    ///      "year",
    ///      "musicbrainzalbumid",
    ///      "musicbrainzalbumartistid",
    ///      "fanart",
    ///      "thumbnail",
    ///      "artistid"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum AlbumFields : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="description")]
        Description = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre = 8,
        
        [System.Runtime.Serialization.EnumMember(Value="theme")]
        Theme = 16,
        
        [System.Runtime.Serialization.EnumMember(Value="mood")]
        Mood = 32,
        
        [System.Runtime.Serialization.EnumMember(Value="style")]
        Style = 64,
        
        [System.Runtime.Serialization.EnumMember(Value="type")]
        Type = 128,
        
        [System.Runtime.Serialization.EnumMember(Value="albumlabel")]
        AlbumLabel = 256,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating = 512,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year = 1024,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzalbumid")]
        MusicBrainzAlbumId = 2048,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzalbumartistid")]
        MusicBrainzAlbumArtistId = 4096,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 8192,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 16384,
        
        [System.Runtime.Serialization.EnumMember(Value="artistid")]
        ArtistId = 32768,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 65535,
    }
}
