//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Audio.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Audio.Fields.Song
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "Audio.Fields.Song",
    ///  "items": {
    ///    "enums": [
    ///      "title",
    ///      "artist",
    ///      "albumartist",
    ///      "genre",
    ///      "year",
    ///      "rating",
    ///      "album",
    ///      "track",
    ///      "duration",
    ///      "comment",
    ///      "lyrics",
    ///      "musicbrainztrackid",
    ///      "musicbrainzartistid",
    ///      "musicbrainzalbumid",
    ///      "musicbrainzalbumartistid",
    ///      "playcount",
    ///      "fanart",
    ///      "thumbnail",
    ///      "file",
    ///      "artistid",
    ///      "albumid"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    [System.Flags()]
    public enum SongFields : long {
        
        [Newtonsoft.Json.JsonIgnore()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title = 1,
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist = 2,
        
        [System.Runtime.Serialization.EnumMember(Value="albumartist")]
        AlbumArtist = 4,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre = 8,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year = 16,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating = 32,
        
        [System.Runtime.Serialization.EnumMember(Value="album")]
        Album = 64,
        
        [System.Runtime.Serialization.EnumMember(Value="track")]
        Track = 128,
        
        [System.Runtime.Serialization.EnumMember(Value="duration")]
        Duration = 256,
        
        [System.Runtime.Serialization.EnumMember(Value="comment")]
        Comment = 512,
        
        [System.Runtime.Serialization.EnumMember(Value="lyrics")]
        Lyrics = 1024,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainztrackid")]
        MusicBrainzTrackId = 2048,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzartistid")]
        MusicBrainzArtistId = 4096,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzalbumid")]
        MusicBrainzAlbumId = 8192,
        
        [System.Runtime.Serialization.EnumMember(Value="musicbrainzalbumartistid")]
        MusicBrainzAlbumArtistId = 16384,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount = 32768,
        
        [System.Runtime.Serialization.EnumMember(Value="fanart")]
        FanArt = 65536,
        
        [System.Runtime.Serialization.EnumMember(Value="thumbnail")]
        Thumbnail = 131072,
        
        [System.Runtime.Serialization.EnumMember(Value="file")]
        File = 262144,
        
        [System.Runtime.Serialization.EnumMember(Value="artistid")]
        ArtistId = 524288,
        
        [System.Runtime.Serialization.EnumMember(Value="albumid")]
        AlbumId = 1048576,
        
        [Newtonsoft.Json.JsonIgnore()]
        All = 2097151,
    }
}
