//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.order
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "ascending",
    ///  "enums": [
    ///    "ascending",
    ///    "descending"
    ///  ],
    ///  "type": "string"
    ///}
    /// </json>
    public enum Orders : long {
        
        [System.Runtime.Serialization.EnumMember(Value="ascending")]
        Ascending,
        
        [System.Runtime.Serialization.EnumMember(Value="descending")]
        Descending,
    }
}
