//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.System.Property {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// System.Property.Name
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "canshutdown",
    ///  "enums": [
    ///    "canshutdown",
    ///    "cansuspend",
    ///    "canhibernate",
    ///    "canreboot"
    ///  ],
    ///  "id": "System.Property.Name",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Name : long {
        
        [System.Runtime.Serialization.EnumMember(Value="canshutdown")]
        CanShutdown,
        
        [System.Runtime.Serialization.EnumMember(Value="cansuspend")]
        CanSuspend,
        
        [System.Runtime.Serialization.EnumMember(Value="canhibernate")]
        CanHibernate,
        
        [System.Runtime.Serialization.EnumMember(Value="canreboot")]
        CanReboot,
    }
}
