//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Filter.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Filter.Fields.Albums
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "genre",
    ///  "enums": [
    ///    "genre",
    ///    "album",
    ///    "artist",
    ///    "albumartist",
    ///    "year",
    ///    "review",
    ///    "themes",
    ///    "moods",
    ///    "styles",
    ///    "type",
    ///    "label",
    ///    "rating",
    ///    "playcount",
    ///    "playlist"
    ///  ],
    ///  "id": "List.Filter.Fields.Albums",
    ///  "type": "string"
    ///}
    /// </json>
    public enum AlbumS : long {
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre,
        
        [System.Runtime.Serialization.EnumMember(Value="album")]
        Album,
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist,
        
        [System.Runtime.Serialization.EnumMember(Value="albumartist")]
        AlbumArtist,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year,
        
        [System.Runtime.Serialization.EnumMember(Value="review")]
        Review,
        
        [System.Runtime.Serialization.EnumMember(Value="themes")]
        Themes,
        
        [System.Runtime.Serialization.EnumMember(Value="moods")]
        Moods,
        
        [System.Runtime.Serialization.EnumMember(Value="styles")]
        Styles,
        
        [System.Runtime.Serialization.EnumMember(Value="type")]
        Type,
        
        [System.Runtime.Serialization.EnumMember(Value="label")]
        Label,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount,
        
        [System.Runtime.Serialization.EnumMember(Value="playlist")]
        Playlist,
    }
}
