//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Filter.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Filter.Fields.Artists
    /// </jsonId>
    /// <json>
    /// {
    ///  "enums": [
    ///    "artist",
    ///    "genre",
    ///    "moods",
    ///    "styles",
    ///    "instruments",
    ///    "biography",
    ///    "born",
    ///    "bandformed",
    ///    "disbanded",
    ///    "died",
    ///    "playlist"
    ///  ],
    ///  "id": "List.Filter.Fields.Artists",
    ///  "required": true,
    ///  "type": "string"
    ///}
    /// </json>
    public enum ArtistS : long {
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre,
        
        [System.Runtime.Serialization.EnumMember(Value="moods")]
        Moods,
        
        [System.Runtime.Serialization.EnumMember(Value="styles")]
        Styles,
        
        [System.Runtime.Serialization.EnumMember(Value="instruments")]
        Instruments,
        
        [System.Runtime.Serialization.EnumMember(Value="biography")]
        Biography,
        
        [System.Runtime.Serialization.EnumMember(Value="born")]
        Born,
        
        [System.Runtime.Serialization.EnumMember(Value="bandformed")]
        Bandformed,
        
        [System.Runtime.Serialization.EnumMember(Value="disbanded")]
        Disbanded,
        
        [System.Runtime.Serialization.EnumMember(Value="died")]
        Died,
        
        [System.Runtime.Serialization.EnumMember(Value="playlist")]
        Playlist,
    }
}
