//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Filter.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Filter.Fields.MusicVideos
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "title",
    ///  "enums": [
    ///    "title",
    ///    "genre",
    ///    "album",
    ///    "year",
    ///    "artist",
    ///    "filename",
    ///    "path",
    ///    "playcount",
    ///    "lastplayed",
    ///    "time",
    ///    "director",
    ///    "studio",
    ///    "plot",
    ///    "dateadded",
    ///    "videoresolution",
    ///    "audiochannels",
    ///    "videocodec",
    ///    "audiocodec",
    ///    "audiolanguage",
    ///    "subtitlelanguage",
    ///    "videoaspect",
    ///    "playlist"
    ///  ],
    ///  "id": "List.Filter.Fields.MusicVideos",
    ///  "type": "string"
    ///}
    /// </json>
    public enum MusicVideoS : long {
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre,
        
        [System.Runtime.Serialization.EnumMember(Value="album")]
        Album,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year,
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist,
        
        [System.Runtime.Serialization.EnumMember(Value="filename")]
        FileName,
        
        [System.Runtime.Serialization.EnumMember(Value="path")]
        Path,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount,
        
        [System.Runtime.Serialization.EnumMember(Value="lastplayed")]
        LastPlayed,
        
        [System.Runtime.Serialization.EnumMember(Value="time")]
        Time,
        
        [System.Runtime.Serialization.EnumMember(Value="director")]
        Director,
        
        [System.Runtime.Serialization.EnumMember(Value="studio")]
        Studio,
        
        [System.Runtime.Serialization.EnumMember(Value="plot")]
        Plot,
        
        [System.Runtime.Serialization.EnumMember(Value="dateadded")]
        Dateadded,
        
        [System.Runtime.Serialization.EnumMember(Value="videoresolution")]
        VideoResolution,
        
        [System.Runtime.Serialization.EnumMember(Value="audiochannels")]
        AudioChannels,
        
        [System.Runtime.Serialization.EnumMember(Value="videocodec")]
        VideoCodec,
        
        [System.Runtime.Serialization.EnumMember(Value="audiocodec")]
        AudioCodec,
        
        [System.Runtime.Serialization.EnumMember(Value="audiolanguage")]
        AudioLanguage,
        
        [System.Runtime.Serialization.EnumMember(Value="subtitlelanguage")]
        SubtitleLanguage,
        
        [System.Runtime.Serialization.EnumMember(Value="videoaspect")]
        VideoAspect,
        
        [System.Runtime.Serialization.EnumMember(Value="playlist")]
        Playlist,
    }
}
