//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Filter.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Filter.Fields.Songs
    /// </jsonId>
    /// <json>
    /// {
    ///  "enums": [
    ///    "genre",
    ///    "album",
    ///    "artist",
    ///    "albumartist",
    ///    "title",
    ///    "year",
    ///    "time",
    ///    "tracknumber",
    ///    "filename",
    ///    "path",
    ///    "playcount",
    ///    "lastplayed",
    ///    "rating",
    ///    "comment",
    ///    "dateadded",
    ///    "playlist"
    ///  ],
    ///  "id": "List.Filter.Fields.Songs",
    ///  "required": true,
    ///  "type": "string"
    ///}
    /// </json>
    public enum SongS : long {
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre,
        
        [System.Runtime.Serialization.EnumMember(Value="album")]
        Album,
        
        [System.Runtime.Serialization.EnumMember(Value="artist")]
        Artist,
        
        [System.Runtime.Serialization.EnumMember(Value="albumartist")]
        AlbumArtist,
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year,
        
        [System.Runtime.Serialization.EnumMember(Value="time")]
        Time,
        
        [System.Runtime.Serialization.EnumMember(Value="tracknumber")]
        TrackNumber,
        
        [System.Runtime.Serialization.EnumMember(Value="filename")]
        FileName,
        
        [System.Runtime.Serialization.EnumMember(Value="path")]
        Path,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount,
        
        [System.Runtime.Serialization.EnumMember(Value="lastplayed")]
        LastPlayed,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating,
        
        [System.Runtime.Serialization.EnumMember(Value="comment")]
        Comment,
        
        [System.Runtime.Serialization.EnumMember(Value="dateadded")]
        Dateadded,
        
        [System.Runtime.Serialization.EnumMember(Value="playlist")]
        Playlist,
    }
}
