//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Filter.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Filter.Fields.TVShows
    /// </jsonId>
    /// <json>
    /// {
    ///  "enums": [
    ///    "title",
    ///    "plot",
    ///    "status",
    ///    "votes",
    ///    "rating",
    ///    "year",
    ///    "genre",
    ///    "director",
    ///    "actor",
    ///    "numepisodes",
    ///    "numwatched",
    ///    "playcount",
    ///    "path",
    ///    "studio",
    ///    "mpaarating",
    ///    "dateadded",
    ///    "lastplayed",
    ///    "inprogress",
    ///    "playlist"
    ///  ],
    ///  "id": "List.Filter.Fields.TVShows",
    ///  "required": true,
    ///  "type": "string"
    ///}
    /// </json>
    public enum TVShowS : long {
        
        [System.Runtime.Serialization.EnumMember(Value="title")]
        Title,
        
        [System.Runtime.Serialization.EnumMember(Value="plot")]
        Plot,
        
        [System.Runtime.Serialization.EnumMember(Value="status")]
        Status,
        
        [System.Runtime.Serialization.EnumMember(Value="votes")]
        Votes,
        
        [System.Runtime.Serialization.EnumMember(Value="rating")]
        Rating,
        
        [System.Runtime.Serialization.EnumMember(Value="year")]
        Year,
        
        [System.Runtime.Serialization.EnumMember(Value="genre")]
        Genre,
        
        [System.Runtime.Serialization.EnumMember(Value="director")]
        Director,
        
        [System.Runtime.Serialization.EnumMember(Value="actor")]
        Actor,
        
        [System.Runtime.Serialization.EnumMember(Value="numepisodes")]
        Numepisodes,
        
        [System.Runtime.Serialization.EnumMember(Value="numwatched")]
        Numwatched,
        
        [System.Runtime.Serialization.EnumMember(Value="playcount")]
        PlayCount,
        
        [System.Runtime.Serialization.EnumMember(Value="path")]
        Path,
        
        [System.Runtime.Serialization.EnumMember(Value="studio")]
        Studio,
        
        [System.Runtime.Serialization.EnumMember(Value="mpaarating")]
        Mpaarating,
        
        [System.Runtime.Serialization.EnumMember(Value="dateadded")]
        Dateadded,
        
        [System.Runtime.Serialization.EnumMember(Value="lastplayed")]
        LastPlayed,
        
        [System.Runtime.Serialization.EnumMember(Value="inprogress")]
        Inprogress,
        
        [System.Runtime.Serialization.EnumMember(Value="playlist")]
        Playlist,
    }
}
