//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Playlist {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Playlist.Type
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "unknown",
    ///  "enums": [
    ///    "unknown",
    ///    "video",
    ///    "audio",
    ///    "picture",
    ///    "mixed"
    ///  ],
    ///  "id": "Playlist.Type",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Type : long {
        
        [System.Runtime.Serialization.EnumMember(Value="unknown")]
        Unknown,
        
        [System.Runtime.Serialization.EnumMember(Value="video")]
        Video,
        
        [System.Runtime.Serialization.EnumMember(Value="audio")]
        Audio,
        
        [System.Runtime.Serialization.EnumMember(Value="picture")]
        Picture,
        
        [System.Runtime.Serialization.EnumMember(Value="mixed")]
        Mixed,
    }
}
