//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Filter {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Filter.Operators
    /// </jsonId>
    /// <json>
    /// {
    ///  "enums": [
    ///    "contains",
    ///    "doesnotcontain",
    ///    "is",
    ///    "isnot",
    ///    "startswith",
    ///    "endswith",
    ///    "greaterthan",
    ///    "lessthan",
    ///    "after",
    ///    "before",
    ///    "inthelast",
    ///    "notinthelast",
    ///    "true",
    ///    "false",
    ///    "between"
    ///  ],
    ///  "id": "List.Filter.Operators",
    ///  "required": true,
    ///  "type": "string"
    ///}
    /// </json>
    public enum Operators : long {
        
        [System.Runtime.Serialization.EnumMember(Value="contains")]
        Contains,
        
        [System.Runtime.Serialization.EnumMember(Value="doesnotcontain")]
        Doesnotcontain,
        
        [System.Runtime.Serialization.EnumMember(Value="is")]
        Is,
        
        [System.Runtime.Serialization.EnumMember(Value="isnot")]
        Isnot,
        
        [System.Runtime.Serialization.EnumMember(Value="startswith")]
        Startswith,
        
        [System.Runtime.Serialization.EnumMember(Value="endswith")]
        Endswith,
        
        [System.Runtime.Serialization.EnumMember(Value="greaterthan")]
        Greaterthan,
        
        [System.Runtime.Serialization.EnumMember(Value="lessthan")]
        Lessthan,
        
        [System.Runtime.Serialization.EnumMember(Value="after")]
        After,
        
        [System.Runtime.Serialization.EnumMember(Value="before")]
        Before,
        
        [System.Runtime.Serialization.EnumMember(Value="inthelast")]
        Inthelast,
        
        [System.Runtime.Serialization.EnumMember(Value="notinthelast")]
        Notinthelast,
        
        [System.Runtime.Serialization.EnumMember(Value="true")]
        True,
        
        [System.Runtime.Serialization.EnumMember(Value="false")]
        False,
        
        [System.Runtime.Serialization.EnumMember(Value="between")]
        Between,
    }
}
