//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.List.Filter {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// List.Filter.Rule
    /// </jsonId>
    /// <json>
    /// {
    ///  "id": "List.Filter.Rule",
    ///  "properties": {
    ///    "operator": {
    ///      "$ref": "List.Filter.Operators",
    ///      "required": true
    ///    },
    ///    "value": {
    ///      "required": true,
    ///      "type": [
    ///        {
    ///          "type": "string"
    ///        },
    ///        {
    ///          "items": {
    ///            "type": "string"
    ///          },
    ///          "type": "array"
    ///        }
    ///      ]
    ///    }
    ///  },
    ///  "type": "object"
    ///}
    /// </json>
    public partial class Rule : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private List.Filter.Operators _operator;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="operator")]
        public List.Filter.Operators Operator {
            get {
                return this._operator;
            }
            set {
                this._operator = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Operator = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseEnum<List.Filter.Operators>(json, "operator");
            this.ParseExtension(json);
        }
    }
}
