//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Player.Notifications.Item {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Player.Notifications.Item.Type
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "unknown",
    ///  "enums": [
    ///    "unknown",
    ///    "movie",
    ///    "episode",
    ///    "musicvideo",
    ///    "song"
    ///  ],
    ///  "id": "Player.Notifications.Item.Type",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Type : long {
        
        [System.Runtime.Serialization.EnumMember(Value="unknown")]
        Unknown,
        
        [System.Runtime.Serialization.EnumMember(Value="movie")]
        Movie,
        
        [System.Runtime.Serialization.EnumMember(Value="episode")]
        Episode,
        
        [System.Runtime.Serialization.EnumMember(Value="musicvideo")]
        MusicVideo,
        
        [System.Runtime.Serialization.EnumMember(Value="song")]
        Song,
    }
}
