//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Player.Notifications {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Player.Notifications.Data
    /// </jsonId>
    /// <json>
    /// {
    ///  "id": "Player.Notifications.Data",
    ///  "properties": {
    ///    "item": {
    ///      "$ref": "Notifications.Item",
    ///      "required": true
    ///    },
    ///    "player": {
    ///      "$ref": "Player.Notifications.Player",
    ///      "required": true
    ///    }
    ///  },
    ///  "type": "object"
    ///}
    /// </json>
    public partial class Data : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private Player.Notifications.Player _player;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="player")]
        public Player.Notifications.Player Player {
            get {
                return this._player;
            }
            set {
                this._player = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Player = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Player.Notifications.Player>(json, "player");
            this.ParseExtension(json);
        }
    }
}
