//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Application.Property {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Application.Property.tag
    /// </jsonId>
    /// <json>
    /// {
    ///  "enums": [
    ///    "prealpha",
    ///    "alpha",
    ///    "beta",
    ///    "releasecandidate",
    ///    "stable"
    ///  ],
    ///  "required": true,
    ///  "type": "string"
    ///}
    /// </json>
    public enum Tag : long {
        
        [System.Runtime.Serialization.EnumMember(Value="prealpha")]
        Prealpha,
        
        [System.Runtime.Serialization.EnumMember(Value="alpha")]
        Alpha,
        
        [System.Runtime.Serialization.EnumMember(Value="beta")]
        Beta,
        
        [System.Runtime.Serialization.EnumMember(Value="releasecandidate")]
        Releasecandidate,
        
        [System.Runtime.Serialization.EnumMember(Value="stable")]
        Stable,
    }
}
