//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Application.Property {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Application.Property.Value
    /// </jsonId>
    /// <json>
    /// {
    ///  "id": "Application.Property.Value",
    ///  "properties": {
    ///    "muted": {
    ///      "default": false,
    ///      "type": "boolean"
    ///    },
    ///    "name": {
    ///      "default": "",
    ///      "minLength": 1,
    ///      "type": "string"
    ///    },
    ///    "version": {
    ///      "properties": {
    ///        "major": {
    ///          "minimum": 0,
    ///          "required": true,
    ///          "type": "integer"
    ///        },
    ///        "minor": {
    ///          "minimum": 0,
    ///          "required": true,
    ///          "type": "integer"
    ///        },
    ///        "revision": {
    ///          "default": null,
    ///          "type": [
    ///            {
    ///              "type": "string"
    ///            },
    ///            {
    ///              "type": "integer"
    ///            }
    ///          ]
    ///        },
    ///        "tag": {
    ///          "enums": [
    ///            "prealpha",
    ///            "alpha",
    ///            "beta",
    ///            "releasecandidate",
    ///            "stable"
    ///          ],
    ///          "required": true,
    ///          "type": "string"
    ///        }
    ///      },
    ///      "type": "object"
    ///    },
    ///    "volume": {
    ///      "default": 0,
    ///      "maximum": 100,
    ///      "minimum": 0,
    ///      "type": "integer"
    ///    }
    ///  },
    ///  "type": "object"
    ///}
    /// </json>
    public partial class Value : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private System.Nullable<bool> _muted = false;
        
        private string _name = "";
        
        private Object _version;
        
        private System.Nullable<int> _volume = 0;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        /// <remarks>Default: 'False'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="muted")]
        public System.Nullable<bool> Muted {
            get {
                return this._muted;
            }
            set {
                this._muted = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="name")]
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="version")]
        public Object Version {
            get {
                return this._version;
            }
            set {
                this._version = value;
            }
        }
        
        /// <remarks>Minimum: '0'  Maximum: '0'  Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="volume")]
        public System.Nullable<int> Volume {
            get {
                return this._volume;
            }
            set {
                this._volume = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Muted = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<bool>>(json, "muted", false);
            this.Name = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "name", "");
            this.Version = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseJsonObject<Object>(json, "version");
            this.Volume = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "volume", 0);
            this.ParseExtension(json);
        }
    }
}
