//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.PVR.Channel {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// PVR.Channel.Type
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "tv",
    ///  "enums": [
    ///    "tv",
    ///    "radio"
    ///  ],
    ///  "id": "PVR.Channel.Type",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Type : long {
        
        [System.Runtime.Serialization.EnumMember(Value="tv")]
        TV,
        
        [System.Runtime.Serialization.EnumMember(Value="radio")]
        Radio,
    }
}
