//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Player.Audio {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Player.Audio.Stream
    /// </jsonId>
    /// <json>
    /// {
    ///  "id": "Player.Audio.Stream",
    ///  "properties": {
    ///    "index": {
    ///      "minimum": 0,
    ///      "required": true,
    ///      "type": "integer"
    ///    },
    ///    "language": {
    ///      "required": true,
    ///      "type": "string"
    ///    },
    ///    "name": {
    ///      "required": true,
    ///      "type": "string"
    ///    }
    ///  },
    ///  "type": "object"
    ///}
    /// </json>
    public partial class AudioStream : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private int _index;
        
        private string _language;
        
        private string _name;
        
        /// <remarks>Minimum: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="index")]
        public int Index {
            get {
                return this._index;
            }
            set {
                this._index = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="language")]
        public string Language {
            get {
                return this._language;
            }
            set {
                this._language = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="name")]
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Index = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<int>(json, "index");
            this.Language = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "language");
            this.Name = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "name");
        }
    }
}
