//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Audio.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Audio.Details.Album
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Audio.Details.Media",
    ///  "id": "Audio.Details.Album",
    ///  "properties": {
    ///    "albumid": {
    ///      "$ref": "Library.Id",
    ///      "required": true
    ///    },
    ///    "albumlabel": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "description": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "mood": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "playcount": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    },
    ///    "style": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "theme": {
    ///      "$ref": "Array.String"
    ///    },
    ///    "type": {
    ///      "default": "",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Album : JeanRichard.Xbmc.Lib.XbmcEntities.Audio.Details.Media {
        
        private System.Nullable<int> _albumId = -1;
        
        private string _albumLabel = "";
        
        private string _description = "";
        
        private string[] _mood;
        
        private System.Nullable<int> _playCount = 0;
        
        private string[] _style;
        
        private string[] _theme;
        
        private string _type = "";
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        /// <remarks>Minimum: '1'  Default: '-1'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="albumid")]
        public System.Nullable<int> AlbumId {
            get {
                return this._albumId;
            }
            set {
                this._albumId = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="albumlabel")]
        public string AlbumLabel {
            get {
                return this._albumLabel;
            }
            set {
                this._albumLabel = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="description")]
        public string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="mood")]
        public string[] Mood {
            get {
                return this._mood;
            }
            set {
                this._mood = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="playcount")]
        public System.Nullable<int> PlayCount {
            get {
                return this._playCount;
            }
            set {
                this._playCount = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="style")]
        public string[] Style {
            get {
                return this._style;
            }
            set {
                this._style = value;
            }
        }
        
        [Newtonsoft.Json.JsonProperty(PropertyName="theme")]
        public string[] Theme {
            get {
                return this._theme;
            }
            set {
                this._theme = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="type")]
        public string Type {
            get {
                return this._type;
            }
            set {
                this._type = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.AlbumId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "albumid", -1);
            this.AlbumLabel = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "albumlabel", "");
            this.Description = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "description", "");
            this.Mood = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "mood");
            this.PlayCount = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "playcount", 0);
            this.Style = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "style");
            this.Theme = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "theme");
            this.Type = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "type", "");
            this.ParseExtension(json);
        }
    }
}
