//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Audio.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Audio.Details.Base
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Media.Details.Base",
    ///  "id": "Audio.Details.Base",
    ///  "properties": {
    ///    "genre": {
    ///      "$ref": "Array.String"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class AudioDetailsBase : JeanRichard.Xbmc.Lib.XbmcEntities.Media.MediaDetailsBase {
        
        private string[] _genre;
        
partial void ParseExtension(Newtonsoft.Json.Linq.JToken json);
        
        [Newtonsoft.Json.JsonProperty(PropertyName="genre")]
        public string[] Genre {
            get {
                return this._genre;
            }
            set {
                this._genre = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Genre = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleArrayValue<string>(json, "genre");
            this.ParseExtension(json);
        }
    }
}
