//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Audio.Details {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Audio.Details.Media
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Audio.Details.Base",
    ///  "id": "Audio.Details.Media",
    ///  "properties": {
    ///    "artist": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "musicbrainzalbumartistid": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "musicbrainzalbumid": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "rating": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    },
    ///    "title": {
    ///      "default": "",
    ///      "type": "string"
    ///    },
    ///    "year": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// </json>
    public partial class Media : JeanRichard.Xbmc.Lib.XbmcEntities.Audio.Details.AudioDetailsBase {
        
        private string _artist;
        
        private string _musicBrainzAlbumArtistId = "";
        
        private string _musicBrainzAlbumId = "";
        
        private System.Nullable<int> _rating = 0;
        
        private string _title = "";
        
        private System.Nullable<int> _year = 0;
        
        [Newtonsoft.Json.JsonProperty(PropertyName="artist")]
        public string Artist {
            get {
                return this._artist;
            }
            set {
                this._artist = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="musicbrainzalbumartistid")]
        public string MusicBrainzAlbumArtistId {
            get {
                return this._musicBrainzAlbumArtistId;
            }
            set {
                this._musicBrainzAlbumArtistId = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="musicbrainzalbumid")]
        public string MusicBrainzAlbumId {
            get {
                return this._musicBrainzAlbumId;
            }
            set {
                this._musicBrainzAlbumId = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="rating")]
        public System.Nullable<int> Rating {
            get {
                return this._rating;
            }
            set {
                this._rating = value;
            }
        }
        
        /// <remarks>Default: ''</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="title")]
        public string Title {
            get {
                return this._title;
            }
            set {
                this._title = value;
            }
        }
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="year")]
        public System.Nullable<int> Year {
            get {
                return this._year;
            }
            set {
                this._year = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Artist = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "artist");
            this.MusicBrainzAlbumArtistId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "musicbrainzalbumartistid", "");
            this.MusicBrainzAlbumId = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "musicbrainzalbumid", "");
            this.Rating = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "rating", 0);
            this.Title = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<string>(json, "title", "");
            this.Year = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "year", 0);
        }
    }
}
