//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Input {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Input.Action
    /// </jsonId>
    /// <json>
    /// {
    ///  "enums": [
    ///    "left",
    ///    "right",
    ///    "up",
    ///    "down",
    ///    "pageup",
    ///    "pagedown",
    ///    "select",
    ///    "highlight",
    ///    "parentdir",
    ///    "parentfolder",
    ///    "back",
    ///    "previousmenu",
    ///    "info",
    ///    "pause",
    ///    "stop",
    ///    "skipnext",
    ///    "skipprevious",
    ///    "fullscreen",
    ///    "aspectratio",
    ///    "stepforward",
    ///    "stepback",
    ///    "bigstepforward",
    ///    "bigstepback",
    ///    "osd",
    ///    "showsubtitles",
    ///    "nextsubtitle",
    ///    "codecinfo",
    ///    "nextpicture",
    ///    "previouspicture",
    ///    "zoomout",
    ///    "zoomin",
    ///    "playlist",
    ///    "queue",
    ///    "zoomnormal",
    ///    "zoomlevel1",
    ///    "zoomlevel2",
    ///    "zoomlevel3",
    ///    "zoomlevel4",
    ///    "zoomlevel5",
    ///    "zoomlevel6",
    ///    "zoomlevel7",
    ///    "zoomlevel8",
    ///    "zoomlevel9",
    ///    "nextcalibration",
    ///    "resetcalibration",
    ///    "analogmove",
    ///    "rotate",
    ///    "rotateccw",
    ///    "close",
    ///    "subtitledelayminus",
    ///    "subtitledelay",
    ///    "subtitledelayplus",
    ///    "audiodelayminus",
    ///    "audiodelay",
    ///    "audiodelayplus",
    ///    "subtitleshiftup",
    ///    "subtitleshiftdown",
    ///    "subtitlealign",
    ///    "audionextlanguage",
    ///    "verticalshiftup",
    ///    "verticalshiftdown",
    ///    "nextresolution",
    ///    "audiotoggledigital",
    ///    "number0",
    ///    "number1",
    ///    "number2",
    ///    "number3",
    ///    "number4",
    ///    "number5",
    ///    "number6",
    ///    "number7",
    ///    "number8",
    ///    "number9",
    ///    "osdleft",
    ///    "osdright",
    ///    "osdup",
    ///    "osddown",
    ///    "osdselect",
    ///    "osdvalueplus",
    ///    "osdvalueminus",
    ///    "smallstepback",
    ///    "fastforward",
    ///    "rewind",
    ///    "play",
    ///    "playpause",
    ///    "delete",
    ///    "copy",
    ///    "move",
    ///    "mplayerosd",
    ///    "hidesubmenu",
    ///    "screenshot",
    ///    "rename",
    ///    "togglewatched",
    ///    "scanitem",
    ///    "reloadkeymaps",
    ///    "volumeup",
    ///    "volumedown",
    ///    "mute",
    ///    "backspace",
    ///    "scrollup",
    ///    "scrolldown",
    ///    "analogfastforward",
    ///    "analogrewind",
    ///    "moveitemup",
    ///    "moveitemdown",
    ///    "contextmenu",
    ///    "shift",
    ///    "symbols",
    ///    "cursorleft",
    ///    "cursorright",
    ///    "showtime",
    ///    "analogseekforward",
    ///    "analogseekback",
    ///    "showpreset",
    ///    "presetlist",
    ///    "nextpreset",
    ///    "previouspreset",
    ///    "lockpreset",
    ///    "randompreset",
    ///    "increasevisrating",
    ///    "decreasevisrating",
    ///    "showvideomenu",
    ///    "enter",
    ///    "increaserating",
    ///    "decreaserating",
    ///    "togglefullscreen",
    ///    "nextscene",
    ///    "previousscene",
    ///    "nextletter",
    ///    "prevletter",
    ///    "jumpsms2",
    ///    "jumpsms3",
    ///    "jumpsms4",
    ///    "jumpsms5",
    ///    "jumpsms6",
    ///    "jumpsms7",
    ///    "jumpsms8",
    ///    "jumpsms9",
    ///    "filter",
    ///    "filterclear",
    ///    "filtersms2",
    ///    "filtersms3",
    ///    "filtersms4",
    ///    "filtersms5",
    ///    "filtersms6",
    ///    "filtersms7",
    ///    "filtersms8",
    ///    "filtersms9",
    ///    "firstpage",
    ///    "lastpage",
    ///    "guiprofile",
    ///    "red",
    ///    "green",
    ///    "yellow",
    ///    "blue",
    ///    "increasepar",
    ///    "decreasepar",
    ///    "volampup",
    ///    "volampdown",
    ///    "channelup",
    ///    "channeldown",
    ///    "previouschannelgroup",
    ///    "nextchannelgroup",
    ///    "leftclick",
    ///    "rightclick",
    ///    "middleclick",
    ///    "doubleclick",
    ///    "wheelup",
    ///    "wheeldown",
    ///    "mousedrag",
    ///    "mousemove",
    ///    "noop"
    ///  ],
    ///  "id": "Input.Action",
    ///  "required": true,
    ///  "type": "string"
    ///}
    /// </json>
    public enum Action : long {
        
        [System.Runtime.Serialization.EnumMember(Value="left")]
        Left,
        
        [System.Runtime.Serialization.EnumMember(Value="right")]
        Right,
        
        [System.Runtime.Serialization.EnumMember(Value="up")]
        Up,
        
        [System.Runtime.Serialization.EnumMember(Value="down")]
        Down,
        
        [System.Runtime.Serialization.EnumMember(Value="pageup")]
        Pageup,
        
        [System.Runtime.Serialization.EnumMember(Value="pagedown")]
        Pagedown,
        
        [System.Runtime.Serialization.EnumMember(Value="select")]
        Select,
        
        [System.Runtime.Serialization.EnumMember(Value="highlight")]
        Highlight,
        
        [System.Runtime.Serialization.EnumMember(Value="parentdir")]
        Parentdir,
        
        [System.Runtime.Serialization.EnumMember(Value="parentfolder")]
        Parentfolder,
        
        [System.Runtime.Serialization.EnumMember(Value="back")]
        Back,
        
        [System.Runtime.Serialization.EnumMember(Value="previousmenu")]
        Previousmenu,
        
        [System.Runtime.Serialization.EnumMember(Value="info")]
        Info,
        
        [System.Runtime.Serialization.EnumMember(Value="pause")]
        Pause,
        
        [System.Runtime.Serialization.EnumMember(Value="stop")]
        Stop,
        
        [System.Runtime.Serialization.EnumMember(Value="skipnext")]
        Skipnext,
        
        [System.Runtime.Serialization.EnumMember(Value="skipprevious")]
        Skipprevious,
        
        [System.Runtime.Serialization.EnumMember(Value="fullscreen")]
        FullScreen,
        
        [System.Runtime.Serialization.EnumMember(Value="aspectratio")]
        Aspectratio,
        
        [System.Runtime.Serialization.EnumMember(Value="stepforward")]
        Stepforward,
        
        [System.Runtime.Serialization.EnumMember(Value="stepback")]
        Stepback,
        
        [System.Runtime.Serialization.EnumMember(Value="bigstepforward")]
        Bigstepforward,
        
        [System.Runtime.Serialization.EnumMember(Value="bigstepback")]
        Bigstepback,
        
        [System.Runtime.Serialization.EnumMember(Value="osd")]
        Osd,
        
        [System.Runtime.Serialization.EnumMember(Value="showsubtitles")]
        ShowSubtitleS,
        
        [System.Runtime.Serialization.EnumMember(Value="nextsubtitle")]
        Nextsubtitle,
        
        [System.Runtime.Serialization.EnumMember(Value="codecinfo")]
        Codecinfo,
        
        [System.Runtime.Serialization.EnumMember(Value="nextpicture")]
        Nextpicture,
        
        [System.Runtime.Serialization.EnumMember(Value="previouspicture")]
        Previouspicture,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomout")]
        Zoomout,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomin")]
        Zoomin,
        
        [System.Runtime.Serialization.EnumMember(Value="playlist")]
        Playlist,
        
        [System.Runtime.Serialization.EnumMember(Value="queue")]
        Queue,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomnormal")]
        Zoomnormal,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel1")]
        Zoomlevel1,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel2")]
        Zoomlevel2,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel3")]
        Zoomlevel3,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel4")]
        Zoomlevel4,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel5")]
        Zoomlevel5,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel6")]
        Zoomlevel6,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel7")]
        Zoomlevel7,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel8")]
        Zoomlevel8,
        
        [System.Runtime.Serialization.EnumMember(Value="zoomlevel9")]
        Zoomlevel9,
        
        [System.Runtime.Serialization.EnumMember(Value="nextcalibration")]
        Nextcalibration,
        
        [System.Runtime.Serialization.EnumMember(Value="resetcalibration")]
        Resetcalibration,
        
        [System.Runtime.Serialization.EnumMember(Value="analogmove")]
        Analogmove,
        
        [System.Runtime.Serialization.EnumMember(Value="rotate")]
        Rotate,
        
        [System.Runtime.Serialization.EnumMember(Value="rotateccw")]
        Rotateccw,
        
        [System.Runtime.Serialization.EnumMember(Value="close")]
        Close,
        
        [System.Runtime.Serialization.EnumMember(Value="subtitledelayminus")]
        SubtitleDelayminus,
        
        [System.Runtime.Serialization.EnumMember(Value="subtitledelay")]
        SubtitleDelay,
        
        [System.Runtime.Serialization.EnumMember(Value="subtitledelayplus")]
        SubtitleDelayplus,
        
        [System.Runtime.Serialization.EnumMember(Value="audiodelayminus")]
        AudioDelayminus,
        
        [System.Runtime.Serialization.EnumMember(Value="audiodelay")]
        AudioDelay,
        
        [System.Runtime.Serialization.EnumMember(Value="audiodelayplus")]
        AudioDelayplus,
        
        [System.Runtime.Serialization.EnumMember(Value="subtitleshiftup")]
        SubtitleShiftup,
        
        [System.Runtime.Serialization.EnumMember(Value="subtitleshiftdown")]
        SubtitleShiftdown,
        
        [System.Runtime.Serialization.EnumMember(Value="subtitlealign")]
        SubtitleAlign,
        
        [System.Runtime.Serialization.EnumMember(Value="audionextlanguage")]
        AudioNextlanguage,
        
        [System.Runtime.Serialization.EnumMember(Value="verticalshiftup")]
        Verticalshiftup,
        
        [System.Runtime.Serialization.EnumMember(Value="verticalshiftdown")]
        Verticalshiftdown,
        
        [System.Runtime.Serialization.EnumMember(Value="nextresolution")]
        Nextresolution,
        
        [System.Runtime.Serialization.EnumMember(Value="audiotoggledigital")]
        AudioToggledigital,
        
        [System.Runtime.Serialization.EnumMember(Value="number0")]
        Number0,
        
        [System.Runtime.Serialization.EnumMember(Value="number1")]
        Number1,
        
        [System.Runtime.Serialization.EnumMember(Value="number2")]
        Number2,
        
        [System.Runtime.Serialization.EnumMember(Value="number3")]
        Number3,
        
        [System.Runtime.Serialization.EnumMember(Value="number4")]
        Number4,
        
        [System.Runtime.Serialization.EnumMember(Value="number5")]
        Number5,
        
        [System.Runtime.Serialization.EnumMember(Value="number6")]
        Number6,
        
        [System.Runtime.Serialization.EnumMember(Value="number7")]
        Number7,
        
        [System.Runtime.Serialization.EnumMember(Value="number8")]
        Number8,
        
        [System.Runtime.Serialization.EnumMember(Value="number9")]
        Number9,
        
        [System.Runtime.Serialization.EnumMember(Value="osdleft")]
        Osdleft,
        
        [System.Runtime.Serialization.EnumMember(Value="osdright")]
        Osdright,
        
        [System.Runtime.Serialization.EnumMember(Value="osdup")]
        Osdup,
        
        [System.Runtime.Serialization.EnumMember(Value="osddown")]
        Osddown,
        
        [System.Runtime.Serialization.EnumMember(Value="osdselect")]
        Osdselect,
        
        [System.Runtime.Serialization.EnumMember(Value="osdvalueplus")]
        Osdvalueplus,
        
        [System.Runtime.Serialization.EnumMember(Value="osdvalueminus")]
        Osdvalueminus,
        
        [System.Runtime.Serialization.EnumMember(Value="smallstepback")]
        Smallstepback,
        
        [System.Runtime.Serialization.EnumMember(Value="fastforward")]
        Fastforward,
        
        [System.Runtime.Serialization.EnumMember(Value="rewind")]
        Rewind,
        
        [System.Runtime.Serialization.EnumMember(Value="play")]
        Play,
        
        [System.Runtime.Serialization.EnumMember(Value="playpause")]
        PlayPause,
        
        [System.Runtime.Serialization.EnumMember(Value="delete")]
        Delete,
        
        [System.Runtime.Serialization.EnumMember(Value="copy")]
        Copy,
        
        [System.Runtime.Serialization.EnumMember(Value="move")]
        Move,
        
        [System.Runtime.Serialization.EnumMember(Value="mplayerosd")]
        Mplayerosd,
        
        [System.Runtime.Serialization.EnumMember(Value="hidesubmenu")]
        Hidesubmenu,
        
        [System.Runtime.Serialization.EnumMember(Value="screenshot")]
        Screenshot,
        
        [System.Runtime.Serialization.EnumMember(Value="rename")]
        Rename,
        
        [System.Runtime.Serialization.EnumMember(Value="togglewatched")]
        Togglewatched,
        
        [System.Runtime.Serialization.EnumMember(Value="scanitem")]
        Scanitem,
        
        [System.Runtime.Serialization.EnumMember(Value="reloadkeymaps")]
        Reloadkeymaps,
        
        [System.Runtime.Serialization.EnumMember(Value="volumeup")]
        Volumeup,
        
        [System.Runtime.Serialization.EnumMember(Value="volumedown")]
        Volumedown,
        
        [System.Runtime.Serialization.EnumMember(Value="mute")]
        Mute,
        
        [System.Runtime.Serialization.EnumMember(Value="backspace")]
        Backspace,
        
        [System.Runtime.Serialization.EnumMember(Value="scrollup")]
        Scrollup,
        
        [System.Runtime.Serialization.EnumMember(Value="scrolldown")]
        Scrolldown,
        
        [System.Runtime.Serialization.EnumMember(Value="analogfastforward")]
        Analogfastforward,
        
        [System.Runtime.Serialization.EnumMember(Value="analogrewind")]
        Analogrewind,
        
        [System.Runtime.Serialization.EnumMember(Value="moveitemup")]
        Moveitemup,
        
        [System.Runtime.Serialization.EnumMember(Value="moveitemdown")]
        Moveitemdown,
        
        [System.Runtime.Serialization.EnumMember(Value="contextmenu")]
        Contextmenu,
        
        [System.Runtime.Serialization.EnumMember(Value="shift")]
        Shift,
        
        [System.Runtime.Serialization.EnumMember(Value="symbols")]
        Symbols,
        
        [System.Runtime.Serialization.EnumMember(Value="cursorleft")]
        Cursorleft,
        
        [System.Runtime.Serialization.EnumMember(Value="cursorright")]
        Cursorright,
        
        [System.Runtime.Serialization.EnumMember(Value="showtime")]
        ShowTime,
        
        [System.Runtime.Serialization.EnumMember(Value="analogseekforward")]
        Analogseekforward,
        
        [System.Runtime.Serialization.EnumMember(Value="analogseekback")]
        Analogseekback,
        
        [System.Runtime.Serialization.EnumMember(Value="showpreset")]
        ShowPreset,
        
        [System.Runtime.Serialization.EnumMember(Value="presetlist")]
        Presetlist,
        
        [System.Runtime.Serialization.EnumMember(Value="nextpreset")]
        Nextpreset,
        
        [System.Runtime.Serialization.EnumMember(Value="previouspreset")]
        Previouspreset,
        
        [System.Runtime.Serialization.EnumMember(Value="lockpreset")]
        Lockpreset,
        
        [System.Runtime.Serialization.EnumMember(Value="randompreset")]
        Randompreset,
        
        [System.Runtime.Serialization.EnumMember(Value="increasevisrating")]
        Increasevisrating,
        
        [System.Runtime.Serialization.EnumMember(Value="decreasevisrating")]
        Decreasevisrating,
        
        [System.Runtime.Serialization.EnumMember(Value="showvideomenu")]
        ShowVideoMenu,
        
        [System.Runtime.Serialization.EnumMember(Value="enter")]
        Enter,
        
        [System.Runtime.Serialization.EnumMember(Value="increaserating")]
        Increaserating,
        
        [System.Runtime.Serialization.EnumMember(Value="decreaserating")]
        Decreaserating,
        
        [System.Runtime.Serialization.EnumMember(Value="togglefullscreen")]
        Togglefullscreen,
        
        [System.Runtime.Serialization.EnumMember(Value="nextscene")]
        Nextscene,
        
        [System.Runtime.Serialization.EnumMember(Value="previousscene")]
        Previousscene,
        
        [System.Runtime.Serialization.EnumMember(Value="nextletter")]
        Nextletter,
        
        [System.Runtime.Serialization.EnumMember(Value="prevletter")]
        Prevletter,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms2")]
        Jumpsms2,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms3")]
        Jumpsms3,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms4")]
        Jumpsms4,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms5")]
        Jumpsms5,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms6")]
        Jumpsms6,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms7")]
        Jumpsms7,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms8")]
        Jumpsms8,
        
        [System.Runtime.Serialization.EnumMember(Value="jumpsms9")]
        Jumpsms9,
        
        [System.Runtime.Serialization.EnumMember(Value="filter")]
        Filter,
        
        [System.Runtime.Serialization.EnumMember(Value="filterclear")]
        Filterclear,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms2")]
        Filtersms2,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms3")]
        Filtersms3,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms4")]
        Filtersms4,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms5")]
        Filtersms5,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms6")]
        Filtersms6,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms7")]
        Filtersms7,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms8")]
        Filtersms8,
        
        [System.Runtime.Serialization.EnumMember(Value="filtersms9")]
        Filtersms9,
        
        [System.Runtime.Serialization.EnumMember(Value="firstpage")]
        FirstPage,
        
        [System.Runtime.Serialization.EnumMember(Value="lastpage")]
        LastPage,
        
        [System.Runtime.Serialization.EnumMember(Value="guiprofile")]
        Guiprofile,
        
        [System.Runtime.Serialization.EnumMember(Value="red")]
        Red,
        
        [System.Runtime.Serialization.EnumMember(Value="green")]
        Green,
        
        [System.Runtime.Serialization.EnumMember(Value="yellow")]
        Yellow,
        
        [System.Runtime.Serialization.EnumMember(Value="blue")]
        Blue,
        
        [System.Runtime.Serialization.EnumMember(Value="increasepar")]
        Increasepar,
        
        [System.Runtime.Serialization.EnumMember(Value="decreasepar")]
        Decreasepar,
        
        [System.Runtime.Serialization.EnumMember(Value="volampup")]
        Volampup,
        
        [System.Runtime.Serialization.EnumMember(Value="volampdown")]
        Volampdown,
        
        [System.Runtime.Serialization.EnumMember(Value="channelup")]
        Channelup,
        
        [System.Runtime.Serialization.EnumMember(Value="channeldown")]
        Channeldown,
        
        [System.Runtime.Serialization.EnumMember(Value="previouschannelgroup")]
        Previouschannelgroup,
        
        [System.Runtime.Serialization.EnumMember(Value="nextchannelgroup")]
        Nextchannelgroup,
        
        [System.Runtime.Serialization.EnumMember(Value="leftclick")]
        Leftclick,
        
        [System.Runtime.Serialization.EnumMember(Value="rightclick")]
        Rightclick,
        
        [System.Runtime.Serialization.EnumMember(Value="middleclick")]
        Middleclick,
        
        [System.Runtime.Serialization.EnumMember(Value="doubleclick")]
        Doubleclick,
        
        [System.Runtime.Serialization.EnumMember(Value="wheelup")]
        Wheelup,
        
        [System.Runtime.Serialization.EnumMember(Value="wheeldown")]
        Wheeldown,
        
        [System.Runtime.Serialization.EnumMember(Value="mousedrag")]
        Mousedrag,
        
        [System.Runtime.Serialization.EnumMember(Value="mousemove")]
        Mousemove,
        
        [System.Runtime.Serialization.EnumMember(Value="noop")]
        Noop,
    }
}
