//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.PVR.Fields {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// PVR.Fields.Channel
    /// </jsonId>
    /// <json>
    /// {
    ///  "extends": "Item.Fields.Base",
    ///  "id": "PVR.Fields.Channel",
    ///  "items": {
    ///    "enums": [
    ///      "thumbnail",
    ///      "channeltype",
    ///      "hidden",
    ///      "locked",
    ///      "channel",
    ///      "lastplayed"
    ///    ],
    ///    "type": "string"
    ///  }
    ///}
    /// </json>
    public class Channel : JeanRichard.Xbmc.Lib.JsonRpc.FlagsBase<Channel> {
        
        public static Channel None = new Channel();
        
        public static Channel Thumbnail = new Channel("thumbnail");
        
        public static Channel Channeltype = new Channel("channeltype");
        
        public static Channel Hidden = new Channel("hidden");
        
        public static Channel Locked = new Channel("locked");
        
        public static Channel Channel = new Channel("channel");
        
        public static Channel LastPlayed = new Channel("lastplayed");
        
        public static Channel All = Channel.Combine(Channel.Thumbnail, Channel.Channeltype, Channel.Hidden, Channel.Locked, Channel.Channel, Channel.LastPlayed);
        

        protected Channel(string value) : base(value)
        {}

        public Channel()
        {}
        
    }
}
