//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Player {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Player.Speed
    /// </jsonId>
    /// <json>
    /// {
    ///  "id": "Player.Speed",
    ///  "properties": {
    ///    "speed": {
    ///      "default": 0,
    ///      "type": "integer"
    ///    }
    ///  },
    ///  "required": true,
    ///  "type": "object"
    ///}
    /// </json>
    public partial class PlayerSpeed : JeanRichard.Xbmc.Lib.JsonRpc.JsonRpcItem {
        
        private System.Nullable<int> _speed = 0;
        
        /// <remarks>Default: '0'</remarks>
        [Newtonsoft.Json.JsonProperty(PropertyName="speed")]
        public System.Nullable<int> Speed {
            get {
                return this._speed;
            }
            set {
                this._speed = value;
            }
        }
        
        protected override void Parse(Newtonsoft.Json.Linq.JToken json) {
            base.Parse(json);
            this.Speed = JeanRichard.Xbmc.Lib.JsonHelpers.JObjectExtensions.ParseSimpleValue<System.Nullable<int>>(json, "speed", 0);
        }
    }
}
