//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanRichard.Xbmc.Lib.XbmcEntities.Player {
    using System;
    using System.Runtime.Serialization;
    
    
    /// <jsonId>
    /// Player.Repeat
    /// </jsonId>
    /// <json>
    /// {
    ///  "default": "off",
    ///  "enums": [
    ///    "off",
    ///    "one",
    ///    "all"
    ///  ],
    ///  "id": "Player.Repeat",
    ///  "type": "string"
    ///}
    /// </json>
    public enum Repeat : long {
        
        [System.Runtime.Serialization.EnumMember(Value="off")]
        Off,
        
        [System.Runtime.Serialization.EnumMember(Value="one")]
        One,
        
        [System.Runtime.Serialization.EnumMember(Value="all")]
        All,
    }
}
